### ISSUE TITLE
How can i set the UA(User-Agent ) for the request?

### ISSUE THREAD

**Issue by ztz0223** [ekalinin/sitemap.js#101]
Great for NodeJS plugin, and my question is how to set the UA?

As my site: [www.doocr.com](http://doocr.com), is a single-page web, I need to get the UA string to handle the sitemap request, like the SEO request, could you provide the options for the createsitemap interface?

Thanks.

**Comment by ekalinin** [comment]
Hey, 

It's quite not clear what do you want to do.
`sitemap` — is just xml file generator.
Where and what for do you want to use `User-Agent`?

The only thing i can imagine — it's a get-request handler for express.js.
Something like this:
```javascript
var express = require('express')
  , sm = require('sitemap');

var app = express()
  , sitemap = sm.createSitemap ({
      hostname: 'http://example.com',
      cacheTime: 600000,  // 600 sec cache period
      urls: [
        { url: '/page-1/',  changefreq: 'daily', priority: 0.3 },
        { url: '/page-2/',  changefreq: 'monthly',  priority: 0.7 },
        { url: '/page-3/' } // changefreq: 'weekly',  priority: 0.5
      ]
    });

app.get('/sitemap.xml', function(req, res) {
  var ua = req.headers['user-agent'];
  // if ua == ... {
  res.header('Content-Type', 'application/xml');
  res.send( sitemap.toString() );
  //}
});

app.listen(3000);
```

**Comment by ztz0223** [comment]
Sorry for my late response, there is another scenario for UA, for SEO of single page website, like Google will check the head part to check the:
**<meta name="fragment" content="!">**
and then send another request with a query string:  **?_escaped_fragment_**
So we dev our site to handle this, and then the prerendering for the static page, but a lot of the spider wont check the fragment part, and wont send the uery string:  **?_escaped_fragment_**, so we need to check the UA and build the query string.

So, we need the UA or query string while doing the sitemap.xml.

And also you can take my site: [doocr.com](http://doocr.com) as a test example, mysite is single page website, without the UA or query string, the sitemap will not be built successfully. 

Thanks,
Rock.

**Comment by ortonomy** [comment]
@ekalinin - actually, I can think of a use case for this.

The site I'm trying to build a site map for: Only from that static XML at https://disneyland.disney.go.com/ will detect that your 'browser' is out of date  if you do not supply a user-agent in an 'up-to-date' list. Any crawler building a site map therefore only gets a single page telling you where to download 'the most up to date browser'.

So I'd like to change the headers that the sitemap.js sends so that I can make the server serve me the full site.

Any ideas?

**Comment by derduher** [comment]
This sounds like you need to change the url outside of sitemap based on the useragent.
