### ISSUE TITLE
Unable to use CDATA wrap on urls when using createSitemap

### ISSUE THREAD

**Issue by yongzhihuang** [ekalinin/sitemap.js#103]
Hi, great module!  I ran into this issue where

```
      urls.unshift({
        url: `https://www.${site}.com`,
        changefreq: 'hourly',
        priority: 1.0
      });

      const siteMapByWeek = sm.createSitemap({
        urls
      });

siteMapByWeek.toXML(function handleXML(err, xml) {});
```

throws an error:

 `{ [NoURLProtocolError: Protocol is required] name: 'NoURLProtocolError', message: 'Protocol is required' }`

vs doing this with `buildSitemapIndex` where it doesn't throw that error.

Thanks!

**Comment by ekalinin** [comment]
Hey, thanks for report & patch. Should be fixed now.
