### ISSUE TITLE
Support multiple video "tag"

### ISSUE THREAD

**Issue by Ilshidur** [ekalinin/sitemap.js#110]
Currently, if we create a sitemap like this :

```javascript
sitemap.add({
        // [ ... ]
        video: [{
          // [ ... ]
          tag: ['one', 'two'], // assuming that multiple video tags are passed as an array
          // [ ... ]
        }]
      });
```

the actual sitemap output is :

```xml
// [ ... ]
<video:tag>one,two</video:tag>
// [ ... ]
```

but should be this, [according to Google](https://developers.google.com/webmasters/videosearch/sitemaps#video-sitemap-tag-definitions) :

```xml
// [ ... ]
<video:tag>one</video:tag>
<video:tag>two</video:tag>
// [ ... ]
```

Which means [this code](https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap.js#L203) must loop through the tag and insert a new `<video:tag>` for each tag.

Anyway, thanks for this lib, it has been very helpful to me :+1:

**Comment by michaelBenin** [comment]
Yup just ran into this as well. Seems pretty straight forward to implment. Check for "tags" and iterate over them: https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap.js#L202

**Comment by antimodern** [comment]
Will it be implement? I see its still open

**Comment by Ilshidur** [comment]
This is not implemented, but I guess if somebody opens a PR, it could be.

The changes must be done here : https://github.com/ekalinin/sitemap.js/blob/39cb303e558daa859ab997949d6ff03cf7e254fa/lib/sitemap-item.js#L165

**Comment by Ilshidur** [comment]
[I opened a PR](https://github.com/ekalinin/sitemap.js/pull/172) : https://github.com/ekalinin/sitemap.js/pull/172

**Comment by ekalinin** [comment]
PR was merged. Thanks for that!

**Comment by vtenq** [comment]
@ekalinin seems like this fix wasn't released yet or I miss something?

**Comment by ekalinin** [comment]
> @ekalinin seems like this fix wasn't released yet or I miss something?

You're right. Fixed:
- https://github.com/ekalinin/sitemap.js/releases/tag/2.2.0

**Comment by vtenq** [comment]
cool, thank you a lot!
