### ISSUE TITLE
example of generating multiple sitemaps from a large list of urls?

### ISSUE THREAD

**Issue by anthonyettinger** [ekalinin/sitemap.js#112]

**Comment by NeXTs** [comment]
@ekalinin Hello
Does this plugin supports automatic splitting of large list of url to multiple sitemaps? Or we need to do it manually?

There are [https://github.com/ekalinin/sitemap.js#example-of-sitemap-index](Example of Sitemap Index) in docs, but honestly I didn't get from docs if it's possible to split large list to multiple files automatically.

**Comment by oarashi** [comment]
@ekalinin also wondering about it. Is it possible to split one big sitemap into couple of smaller ones? =) 
Thank you!

**Comment by RichardKCollins** [comment]
What do you need for "documentation needed"?

I have not worked on a GitHub project before. 

I want to run random samples of sites on the Internet to report on accessibility and performance.  I need an easily-shared way for people to run their own surveys, on their and other sites.  My career before I retired was mathematical statistics and global models.  I have been "The Internet Foundation" for 21 year now.  If you can help me learn GitHub, I am happy to help you on whatever you want to do.  If you think I should start with something else, please point me in a good direction.  I just wanted to see how github works by doing something small first.

So, please tell me what to do and somewhat how to do it.  The analysis and writing is easy. What is hard is learning github practices and pathways.  I am using Windows and installed the Github Desktop. I cloned sitemap.js but do not know how to run it or what to do next. My son showed me how to use NodeJs, and I have programmed for more than 50 years. But I do not understand NodeJs directory conventions.  That npm install for sitemap?  Where should I be when I do that?  In the Github folder for sitemap.js?  It is these "where do things go?" questions that are real stumbling blocks for new users.  Myself included.  You cannot enter a house until you know where the door is, and what to do first.

Richard Collins, The Internet Foundation
