### ISSUE TITLE
`del` method requires fully formed urls

### ISSUE THREAD

**Issue by dhritzkiv** [ekalinin/sitemap.js#113]
The `.del` method only seems to work if you pass a fully qualified url (hostname + path) as the argument.

However, the example in the README seems to operate with just the path (no hostname) in both string argument, and object argument forms.

Should the README documentation be updated to reflect the format that `del` is expecting, or should `del` be patched to work with path-only urls?

**Comment by knoxcard** [comment]
Should be path only I am thinking because sitemaps only work for one domain?

**Comment by dhritzkiv** [comment]
I agree, especially since that's what's listed in the documentation

**Comment by ekalinin** [comment]
Hey @dhritzkiv 

> The .del method only seems to work if you pass a fully qualified url (hostname + path) as the argument.

Could you provide any example of this issue?

`.del` & `.add` methods should work with paths only (without domains).
Like here:

- https://github.com/ekalinin/sitemap.js#example-of-dynamic-page-manipulations-into-sitemap

Full path (hostname + path) is created only in `toString` method:

- https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap.js#L192

**Comment by dhritzkiv** [comment]
Hi @ekalinin. Thanks for chiming in.

I've reproduced a case [here on Runkit](https://runkit.com/embed/ab4hk5fu4af5). Note: I used the same version of sitemap.js (v1.2.0) as when I reported this issue initially.

It looks like the problem is fixed in the latest codebase, however. Because it's fixed, I suppose it's safe to close.

**Comment by ekalinin** [comment]
Cool. Thanks @dhritzkiv
