### ISSUE TITLE
package.json not found

### ISSUE THREAD

**Issue by danpersa** [ekalinin/sitemap.js#114]
The code in [this file](https://github.com/ekalinin/sitemap.js/blob/master/index.js) gives me an error, as soon as I create a node module with webpack. The error says that the `package.json` file is not found.
```
if (!module.exports.version) {
  module.exports.version = JSON.parse(
    fs.readFileSync(__dirname + "/package.json", 'utf8')).version;
}
```
Why does the code depend on the package.json file?
Am I configuring it wrongly? Is there an workaround?

**Comment by ekalinin** [comment]
Hey,

This block of code reads a version of the package from [package.json](https://github.com/ekalinin/sitemap.js/blob/master/package.json).
Just to not copy-paste the version (DNRY).

Why there's no such file in your installation? How did you install `sitemap.js`?

**Comment by danpersa** [comment]
I used npm for installing it. In my project, I have the `package.json` file. Then I use `webpack` to create a node distribution, all of code gets concatenated and minified and in the end I have a file called `app.js`. When I try to run this file, `node app.js`, the `sitemap` code in the `app.js` file looks for the `package.json` file, which doesn't exist, as I'm not into the context of the project anymore.

**Comment by danpersa** [comment]
@ekalinin thanks a lot!

**Comment by ekalinin** [comment]
No problem :) Thanks for report.
Please, try new version:
  * https://github.com/ekalinin/sitemap.js/releases/tag/1.12.1
