### ISSUE TITLE
Updated from version 0.8.1 to 1.13.0 and sitemap no longer rendering

### ISSUE THREAD

**Issue by me12722** [ekalinin/sitemap.js#116]
I recently updated my version of the module to incorporate google news articles but after the update my sitemap stopped rendering. 

Here is the sitemap object: Sitemap {
  limit: 50000,
  hostname: 'http://fedev.storied.co/projects/94833010577af9caaae32b1ec23e0df5/',
  urls:
   [ { url: 'home/',
       lastmodISO: '2016-11-18T14:28:45.000Z',
       changefreq: 'daily',
       priority: 0.5 },
     { url: 'about/',
       lastmodISO: '2016-11-18T14:28:45.000Z',
       changefreq: 'daily',
       priority: 0.5 },
     { url: 'contact/',
       lastmodISO: '2016-11-18T14:28:45.000Z',
       changefreq: 'daily',
       priority: 0.5 },
     { url: 'features/',
       lastmodISO: '2016-11-18T14:28:45.000Z',
       changefreq: 'daily',
       priority: 0.5 },
     { url: 'pricing/',
       lastmodISO: '2016-11-18T14:28:45.000Z',
       changefreq: 'daily',
       priority: 0.5 } ],
  cacheResetPeriod: 600000,
  cache: '',
  xslUrl: undefined,
  xmlNs: undefined }

What am I doing wrong?

**Comment by ekalinin** [comment]
Hey @me12722 

Just tested your example:

```
➥ node -v
v7.7.1

➥ cat testing-116.js
var options = {
    limit: 50000,
    hostname: 'http://fedev.storied.co/projects/94833010577af9caaae32b1ec23e0df5/',
    urls: [ 
        {
            url: 'home/',
            lastmodISO: '2016-11-18T14:28:45.000Z',
            changefreq: 'daily',
            priority: 0.5 
        },
        {
            url: 'about/',
            lastmodISO: '2016-11-18T14:28:45.000Z',
            changefreq: 'daily',
            priority: 0.5 
        }],
    cacheResetPeriod: 600000,
    cache: '',
    xslUrl: undefined,
    xmlNs: undefined 
};
var sm = require('sitemap');
var sitemap = sm.createSitemap(options);
console.log(sitemap.toString());

➥ node testing-116.js | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <url>
    <loc>http://fedev.storied.co/projects/94833010577af9caaae32b1ec23e0df5/home/</loc>
    <lastmod>2016-11-18T14:28:45.000Z</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.5</priority>
  </url>
  <url>
    <loc>http://fedev.storied.co/projects/94833010577af9caaae32b1ec23e0df5/about/</loc>
    <lastmod>2016-11-18T14:28:45.000Z</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.5</priority>
  </url>
</urlset>
```

**Comment by me12722** [comment]
Resolved my issue. In version 0.8.1 calling toXML() returned a callback with the first argument self.toString() but now it returns null as the first argument and self.toString() as the second. 

Thanks I appreciate you testing that out for me.
