### ISSUE TITLE
Cannot resolve module "fs"

### ISSUE THREAD

**Issue by sonal241** [ekalinin/sitemap.js#117]
hello,
       I m using your plugin but it not working.show above error.Please tell me what is probem
Thanks

**Comment by ekalinin** [comment]
Hey, 

Show me your code, please. 
What version of the node are you using?

**Comment by sonal241** [comment]
I m using  "@types/node": "^8.0.46" this

**Comment by sonal241** [comment]
**"@types/node": "^8.0.46",**

**Comment by sonal241** [comment]
i am using **"node": "^8.0.46",**

**Comment by sonal241** [comment]
**Example of dynamic page manipulations into sitemap:

var sitemap = sm.createSitemap ({
      hostname: 'http://example.com',
      cacheTime: 600000
    });
sitemap.add({url: '/page-1/'});
sitemap.add({url: '/page-2/', changefreq: 'monthly', priority: 0.7});
sitemap.del({url: '/page-2/'});
sitemap.del('/page-1/');**
added above example In my project but it can't work

**Comment by ekalinin** [comment]
```
➥ node -v
v8.7.0

➥ npm install sitemap
+ sitemap@1.13.0

➥ cat test.js 
var sm = require('sitemap')
var sitemap = sm.createSitemap ({
	hostname: 'http://example.com',
	cacheTime: 600000
});
sitemap.add({url: '/page-1/'});
sitemap.add({url: '/page-2/', changefreq: 'monthly', priority: 0.7});
sitemap.del({url: '/page-2/'});
sitemap.del('/page-1/');
console.log(sitemap.toString());

➥ node test.js | xmllint --format -
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
</urlset>
```

**Comment by sonal241** [comment]
hey USing same code still show same error

**Comment by sonal241** [comment]
I thing problem is from sitemap.js which not getting  **fs**  Module

**Comment by sonal241** [comment]
can you tell me how to return **sitemap.toString()** into xml format

**Comment by ekalinin** [comment]
In my example result from `sitemap.toString()` is exactly XML.

**Comment by sonal241** [comment]
Actually I m using this plugin in vuejs project so i want to return sitemap.toString() on browser but i couldn't do this. result is display in console.log but how can i return on browser .
If you  have any idea about this then please tell me

**Comment by ekalinin** [comment]
I believe it's not possible to use sitemap in the browser atm,

**Comment by sonal241** [comment]
I just want to return data in xml document format  which is displayed  in textformat
Like this
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url> <loc>http://example.com</loc> <lastmod>2017-03-23 20:24:48</lastmod> <changefreq>monthly</changefreq> <priority>0.7</priority> </url></urlset >

**Comment by alexey-kuznetsov** [comment]
Package 'fs' was removed from NPM. So npm downloads empty placeholder instead of package. May be solution is to use 'graceful-fs' instead of 'fs'?

**Comment by derduher** [comment]
I'm confused why would the fs module not resolve while in node?
