### ISSUE TITLE
generate static sitemap.xml from db?

### ISSUE THREAD

**Issue by ralyodio** [ekalinin/sitemap.js#12]
I want to run a cronjob everynight that builds all my urls and writes out to ./public/sitemap.xml

Is this possible?

**Comment by molinto** [comment]
I'm doing this too for articles. 
Is there a way to clear all values from the sitemap & start again as articles can be removed/status updated etc.

Thanks

**Comment by ekalinin** [comment]
> Is there a way to clear all values from the sitemap & start again as articles can be removed/status updated etc.

If you're about clear cache, then there's a method ``Sitemap.clearCache``.
If you're about url list, you can clear it by yourself lke this: ``Sitemap.url = []``

**Comment by molinto** [comment]
Sorry, removed comment as was stupidly using 'fs.writeFileSync; instead of 'fs.writeFile'.

Thank for replying & for your great module :)
Sharry

**Comment by ekalinin** [comment]
> Thank for replying & for your great module :)

No problem :)
