### ISSUE TITLE
Anyway to put <url></url> inside Index Sitemap? 

### ISSUE THREAD

**Issue by kunokdev** [ekalinin/sitemap.js#120]
I am trying to implement sitemap similar to one from BBC.

http://www.bbc.co.uk/sitemap.xml

Basically they have index sitemap with various `<sitemap></sitemap>` links to actual sitemaps, but they also have `<url></url>` at the top for their homepage. 

I am currently using `buildSitemapIndex` method.

**Comment by huntharo** [comment]
This is not supported by the XML sitemaps schema (having a `url` in a sitemap index).

I think we can close this @derduher
