### ISSUE TITLE
'&' Gets Replaced with '&amp;' in URL

### ISSUE THREAD

**Issue by dcurletti** [ekalinin/sitemap.js#124]
Hi there- When I add a url that contains '&', it is replaced with: '&amp;'.  Any reasoning for this that I'm not aware of, or is it possibly a bug?  Thanks!

**Comment by dcurletti** [comment]
I see it, I can pass a `safe` param.

**Comment by dcurletti** [comment]
Actually, not quite sure where I'm supposed to pass the `safe` param.  I passed it to both `.add` and the top level config.

**Comment by dcurletti** [comment]
Whoops, I was passing "false" when it should be "true".

**Comment by santhoshsk1918** [comment]
Where do you pass safe parameter i have tried adding them along with each url `{ url: '/page-1/',  changefreq: 'daily', priority: 0.3, safe: true }` i also tried adding them in .createSitemap({safe: true}) but still the same result all & are getting converted to &amp;.
