### ISSUE TITLE
what is the purpose of the cacheTime option?

### ISSUE THREAD

**Issue by budarin** [ekalinin/sitemap.js#133]
Hi!
what is the purpose of the cacheTime option when using not in web app?

**Comment by ekalinin** [comment]
Hey,

It's a period for cache invalidation. It's useful in cases when you have a huge sitemap.
Each `toString` call includes a lot of work and if you want to reduce the amount of that work it's very handy to use cache.

**Comment by budarin** [comment]
thanks
