### ISSUE TITLE
is there an ability to maintain a list of sitemaps like in sitemap2 ?

### ISSUE THREAD

**Issue by budarin** [ekalinin/sitemap.js#134]
Hi!
We have a complex webapp so its prefferable for us would be to split sitemap for main sections.

**Comment by ekalinin** [comment]
Hey,

Do you mean sitemap index?

https://github.com/ekalinin/sitemap.js#example-of-sitemap-index-as-string

**Comment by budarin** [comment]
am I right?
- I need manually save each sitemaps and give them names
- create sitmap index and put there those names

**Comment by ekalinin** [comment]
In case of using of function `createSitemapIndex` you won't need to do anything by hands. 

Here's an example (from tests):

```
    var tmp = require('os').tmpdir(),
        url1 = 'http://ya.ru',
        url2 = 'http://ya2.ru',
        expectedFiles = [
          tmp + '/sm-test-0.xml.gz',
          tmp + '/sm-test-1.xml.gz',
          tmp + '/sm-test-index.xml'
        ];

    // Cleanup before run test
    removeFilesArray(expectedFiles);

    sm.createSitemapIndex({
      cacheTime: 600000,
      hostname: 'http://www.sitemap.org',
      sitemapName: 'sm-test',
      sitemapSize: 1,
      targetFolder: tmp,
      gzip: true,
      urls: [url1, url2],
      callback: function(err, result) {
        assert.eql(err, null);
        assert.eql(result, true);
        expectedFiles.forEach(function(expectedFile) {
          assert.eql(fs.existsSync(expectedFile), true);
        });
      }
    });
```

where:

* `sm-test-index.xml` is an index
* `sm-test-1.xml.gz` a sitemap with no more than `sitemapSize` urls

**Comment by budarin** [comment]
I'm sorry, but in my opinion, this is a complex interface.
Take a look at this approach:
```js
var fs = require('fs');
var Sitemap = require('sitemap2');

var host = 'http://vk.com';

var sm = new Sitemap({hostName: host});

var movies = new Sitemap({hostName: host});
movies.addUrl('http://vk.com/movies/video-1');
movies.addUrl('http://vk.com/movies/video-n');

var books = new Sitemap({hostName: host});
books.addUrl('http://vk.com/books/book-1');
books.addUrl('http://vk.com/books/book-n');

sm.addSitemap(movies);
sm.addSitemap(books);

sm.save();
```

**Comment by derduher** [comment]
With the latest release sitemap now just focuses on transformation of data. So I don't think this is in scope of the project anymore. I do still welcome PRs if there is room for improvement on api interface design.
