### ISSUE TITLE
documentation for opting out of xmlns:* attributes?

### ISSUE THREAD

**Issue by andyford** [ekalinin/sitemap.js#149]
By default, sitemaps are generated with xmlns:news, xmlns:xhtml, xmlns:mobile, xmlns:image, and xmlns:video, attributes on the 'urlset' element.

I'm no SEO or sitemap expert by any stretch of the imagination, but often these are not relevant and I fear that Google could one day decide that having these attributes when you are not using them will begin to be punished.

Is there any documentation for opting out of these extra attributes?
Should these maybe be opt-in instead of opt-out?
Is there any known re-assurance from Google or elsewhere that you won't suddenly be punished for  having these attributes when they're not really accurate?

Thanks!

**Comment by TimoRuetten** [comment]
This feature would be nice. Because it seems to be missing in this repo we will have to write it by our own.

**Comment by andyford** [comment]
Looking through the sourcecode and the tests, I found that you can pass an argument like
```
xmlNs: 'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"'
```
if you want to opt out of all the other urlset attributes (xmlns:news, xmlns:xhtml, xmlns:mobile, xmlns:image, and xmlns:video)

**Comment by andyford** [comment]
PR: https://github.com/ekalinin/sitemap.js/pull/167

**Comment by JustinBeaudry** [comment]
Is this still an open issue given that #167 was merged?

**Comment by bdrtsky** [comment]
Unfortunately, I found out it doesn't work with `createSitemapIndex`
