### ISSUE TITLE
reading existing xml sitemap

### ISSUE THREAD

**Issue by FadiAboMsalam** [ekalinin/sitemap.js#154]
Hi i am facing the following 

i have dynamic website that adds post everyday and i want to create sitemap index and add post to the sitemap. 
this can be achieved by this library  but as i am still developing more features i want a way to read the xml 
maybe like this 
```
var sitemap = sm.readSitemap({xmlPath:'route/to/xml/file });
then do something like :- sitemap.add({url: '/page-1/'});
```

is this possible to achieve because currently am stuck

PS:- i know there is no issue while the server is up and running meaning 
`var sitemap = sm.createSitemap ({
      hostname: 'http://example.com',
      cacheTime: 600000
    });`
sitemap here will always be defined and accessed but what happens when i restart the server for adding new features

please help me
thanks

**Comment by mtx62** [comment]
Same concern,

**Comment by MarcGodard** [comment]
I am just dynamically deploying it so it is 100% up to date.

**Comment by derduher** [comment]
Implemented. Feedback welcome.
