### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by realityking** [ekalinin/sitemap.js#156]
What do you think about tagging a new major release @ekalinin? Lot's of good changes that have added up :)

**Comment by ekalinin** [comment]
Hey @realityking 

Yeah, will try to tag 2.0 on this week.

**Comment by realityking** [comment]
That's awesome. Thank you!

**Comment by ekalinin** [comment]
@realityking 

https://github.com/ekalinin/sitemap.js/releases/tag/2.0.0

**Comment by realityking** [comment]
Put 2.0.1 in our project and it works flawlessly 👍 

Thanks @ekalinin!
