### ISSUE TITLE
.contains()

### ISSUE THREAD

**Issue by cekvenich** [ekalinin/sitemap.js#159]
How do I find out if the sitemap contains an url already?

So I don't replace by mistake.

**Comment by ekalinin** [comment]
Hi @cekvenich 

There's no such method yet.

here's a simple way (used in [del method](https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap.js#L119)):
```
  key = 'some-url'
  sitemap.urls.forEach(function (elem, index) {
    if (typeof elem === 'string') {
      if (elem === key) {
        console.log('Exists!');
      }
    } else {
      if (elem.url === key) {
        console.log('Exists!');
      }
    }
  });
```

**Comment by ekalinin** [comment]
Good point. Maybe will do it in this way.
