### ISSUE TITLE
lastmod field returns Nan-Nan-Nan

### ISSUE THREAD

**Issue by palakbhansali** [ekalinin/sitemap.js#16]
{ url: '', lastmod: moment().toISOString(), changefreq: 'daily', priority: 0.3 },
    { url: '/culture', lastmod: moment().toISOString(), changefreq: 'monthly', priority: 0.9 },
    { url: '/culture/putting-dent-into-the-universe', lastmod: moment().toISOString(), changefreq: 'monthly', priority: 0.89 },
    { url: '/culture/workmanship-is-the-key', lastmod: moment().toISOString(), changefreq: 'monthly', priority: 0.88 }

We always get Nan-Nan-Nan for the lastmod field in generated sitemap.xml file.

Any idea ??

**Comment by ekalinin** [comment]
Should be fixed in [1.7.0](https://github.com/ekalinin/sitemap.js/releases/tag/1.7.0)
