### ISSUE TITLE
Questions: difference between sitemap.toXML and sitemap.toString()?

### ISSUE THREAD

**Issue by jchungkr** [ekalinin/sitemap.js#169]
Apologize for posting question on the Issues tab
(will delete and move if there is a community / forum)

Also is there a way to generate sitemap with line breaks between the nested tags/nodes? I am getting a xml file that is one continuous stream of tags/nodes.

Thank you 😀

**Comment by ekalinin** [comment]
Hey,

Nope, there's no such method.
But you can do it pretty easy with yourself:

- https://stackoverflow.com/a/16090892

**Comment by jchungkr** [comment]
Thank you for the super fast reply. 
I am using sitemap in aws lamda so I will try some pretty print npm modules.

Also is there a difference between the `sitemap.toXML` and `sitemap.toString()` methods?
