### ISSUE TITLE
'changefreq' and 'priority' should be optional

### ISSUE THREAD

**Issue by nfleury** [ekalinin/sitemap.js#17]
According to http://www.sitemaps.org/protocol.html#xmlTagDefinitions:

These tags are optional: 

- changefreq
- priority

Actually, it seems to be impossible to get rid of them in the generated xml ... 

Even if can understand the '0.5' default value for the priority, I think there is no point for adding it: it will increase the page weight for nothing

I could not find that default value for changefreq was 'weekly' in the specification, but the same goes for this tag

**Comment by bobiblazeski** [comment]
Any update on this ?

**Comment by ekalinin** [comment]
PRs are welcomed!

**Comment by ekalinin** [comment]
Fixed in #62
