### ISSUE TITLE
Question: How to create sub sitemaps?

### ISSUE THREAD

**Issue by gmunisifreddy** [ekalinin/sitemap.js#170]
I want to create a sitemaps that has sub sitemaps. Is it possible to create sub sitemaps?

**Comment by ceefour** [comment]
@gmunisifreddy What you want is a sitemap index that lists individual sitemaps. This use case is already covered in the README, you can read it.

@ekalinin I think you should close this.

**Comment by ekalinin** [comment]
We have 2 examples in README:
- https://github.com/ekalinin/sitemap.js#example-of-sitemap-index-as-string
- https://github.com/ekalinin/sitemap.js#example-of-sitemap-index

**Comment by MarcGodard** [comment]
These examples no longer exist. Anywhere else?

**Comment by derduher** [comment]
@MarcGodard https://github.com/ekalinin/sitemap.js#building-just-the-sitemap-index-file or right below it is the example that auto generates the sitemaps and index.

**Comment by MarcGodard** [comment]
@derduher thanks, I did find that after. I was more looking for a way to do both and couldn't find it (a sitemap that has urls and other sitemaps). After I found what you mentioned, I changed my strategy and used what you mentioned and separated the other urls.
