### ISSUE TITLE
"&" in the links are getting replaced to "&amp;"

### ISSUE THREAD

**Issue by santhoshsk1918** [ekalinin/sitemap.js#173]
URL with & are getting replaced to &amp. This issue was already noted and closed in ['&' Gets Replaced with '&amp;' in URL](https://github.com/ekalinin/sitemap.js/issues/124) with solution not properly specified. In the solution mentioned he mentions safe parameter to be passed but  where do you pass safe parameter i have tried adding them along with each `url { url: '/page-1/a=2&b=1', changefreq: 'daily', priority: 0.3, safe: true }` i also tried adding them in `sm.createSitemap({safe: true})` but still the same result all & are getting converted to &.

**Comment by ekalinin** [comment]
Hey @santhoshsk1918 !

Could you provide an example of your issue?

Here's what i'm getting:

```js
$ cat test.js
'use strict'

const sm = require('sitemap')
const url = 'http://ya.ru/view?widget=3&count>2'
const smi = new sm.SitemapItem({'url': url})

console.log(smi.toString())
```

and:

```bash
$ node test.js                      
<url><loc>http://ya.ru/view?widget=3&amp;count&gt;2</loc></url>
```

**Comment by santhoshsk1918** [comment]
<url><loc>http://ya.ru/view?widget=3&amp;count&gt;2</loc></url>

The output u have is `http://ya.ru/view?widget=3**&amp;**count&gt;2,` here &amp; is not correct url it should have been `http://ya.ru/view?widget=3**&**count>2`

**Comment by ekalinin** [comment]
> The output u have is http://ya.ru/view?widget=3&amp;count&gt;2, here &amp; is not correct. url should have been http://ya.ru/view?widget=3&count>2. & is being encoded as &amp;

Sitemap is a xml document. `&` should be replaced in any xml document with `&amp;`.

Proof:
- https://www.sitemaps.org/protocol.html#escaping
