### ISSUE TITLE
why priority attribute only allowed  Keep one decimal ?

### ISSUE THREAD

**Issue by zhijs** [ekalinin/sitemap.js#176]
I scanned the sitemap descriptive [page](https://www.sitemaps.org/protocol.html#xmlTagDefinitions) , and not found that the priority only allow Keep one decimal, otherwise, I refered the famous sites like [豆瓣](https://www.douban.com), and the priority in his sitemap like '<priority>0.000631481287316</priority>', so,  It seems to me that the priority should not only use one decimal.

**Comment by derduher** [comment]
After reviewing the XSD for sitemap, it would appear sitemap can support precision like this. I'm not sure why you would but I see no reason to disallow it.

**Comment by zhijs** [comment]
get, thanks for you answer
