### ISSUE TITLE
Is there an easy way to use this library with typescript?

### ISSUE THREAD

**Issue by orverduzco** [ekalinin/sitemap.js#178]
I'm trying to port a project I had in JS to TS, and I have a strong dependency on this library. I've tried to find the definitions file without any luck. Is there already a way, or a plan, to make this library usable with Typescript?

**Comment by msheakoski** [comment]
Easy way would be to add allowJs to your tsconfig.json:
```json
{
    "compilerOptions": {
        "allowJs": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "strict": true,
        "target": "esnext"
    }
}
```
You don't get the benefits of autocompletion for the sitemap module, but your TypeScript code still compiles just fine in strict mode with no warnings.
```typescript
const sm = require("sitemap");
const sitemap = sm.createSitemap({hostname: "https://example.com"});
sitemap.add({url: "/mypage", changefreq: "daily"});
console.log(sitemap.toString());
```

**Comment by derduher** [comment]
I just learned some basic TS, I'll look at this this weekend

**Comment by ekalinin** [comment]
It should be easy now to use `sitemap` from typescript.
#183 was merged.
