### ISSUE TITLE
Repo code doesn't match code  npm package

### ISSUE THREAD

**Issue by AndrewHaluza** [ekalinin/sitemap.js#181]
https://github.com/ekalinin/sitemap.js/blob/8ff1e17884a36c6c9a8280bae0847a81d37b7f91/lib/sitemap.js#L299

2.1.0 version both

![image](https://user-images.githubusercontent.com/15956700/57300441-7edde500-70df-11e9-9a32-8a312a8aade0.png)

There is no in npm package :  
```
  if (url instanceof Object) {
      lastmod = url.lastmod ? url.lastmod : lastmod;

      url = url.url;
    }
```

**Comment by ekalinin** [comment]
I have no idea how it could be.
Just uploaded [3.0.0](https://www.npmjs.com/package/sitemap/v/3.0.0) version (in typescript).
