### ISSUE TITLE
[3.0] urls argument should be optional

### ISSUE THREAD

**Issue by msheakoski** [ekalinin/sitemap.js#187]
https://github.com/ekalinin/sitemap.js/blob/9cf26148844467104583b5f3c010c73a21d8ea2d/lib/sitemap.ts#L69

Since the default value of urls is an empty array, the urls argument should also be optional. I ran into this issue because I dynamically build my sitemap after initializing:

```typescript
const sitemap = sm.createSitemap({
    hostname: process.env.SITEMAP_HOSTNAME,
});
sitemap.add("/");
sitemap.add("/some_page");
```

After updating to 3.0, the above code triggers a type error but it works fine in 2.x

**Comment by derduher** [comment]
Good spot, I'll look at this tonight

**Comment by cekvenich** [comment]
This is blocking me since: I can't create sitemap now and docs don't show a working way to create a map.

**Comment by derduher** [comment]
@cekvenich just stick to version 2.x until patched. 3.0.0 was released this morning.

**Comment by cekvenich** [comment]
urls: string is still not optional in 3.1

**Comment by derduher** [comment]
@cekvenich looks like I missed it in the createSitemap function. You can instantiate sitemap directly for now as I did make that optional. See the definition of sitemap for the map of function to constructor.
