### ISSUE TITLE
[3.0] add method no longer handles objects

### ISSUE THREAD

**Issue by msheakoski** [ekalinin/sitemap.js#188]
https://github.com/ekalinin/sitemap.js/blob/9cf26148844467104583b5f3c010c73a21d8ea2d/lib/sitemap.ts#L125

Code like this triggers a TypeScript error after updating to 3.0 due to the add method only accepting a string:
```typescript
sitemap.add({url: "/", changefreq: "daily"});
```

Instead, it should be something like:
```typescript
add (url: string | SiteMapItem): number {
```

**Comment by derduher** [comment]
Good spot. I'll look at this tonight.
