### ISSUE TITLE
Sitemap index can be read, but has errors

### ISSUE THREAD

**Issue by alihesari** [ekalinin/sitemap.js#203]
I got this error in Google search console: **Sitemap index can be read, but has errors**

```
const sitemap = sm.buildSitemapIndex({
      urls: [`${base_url}/pages.xml`, `${base_url}/posts-sitemap1.xml`, ]
});

fs.writeFileSync(`${this.sitemapPath}/sitemap_index.xml`, sitemap.toString());
```

<img width="978" alt="Screen Shot 2019-07-10 at 10 01 12 AM" src="https://user-images.githubusercontent.com/8302633/60942937-b2b0d300-a2f9-11e9-8687-03d181ba881c.png">

**Comment by derduher** [comment]
I have fixed this in master and we will cut a new release shortly.
