### ISSUE TITLE
Amp sitemap error: Your Sitemap or Sitemap index file doesn't properly declare the namespace

### ISSUE THREAD

**Issue by hbinduni** [ekalinin/sitemap.js#207]
Hi, i try to add my sitemap with amp link, but it give me this error:
Previously without amp link, everything seem fine. Google can read my sitemap without any error.

<img width="922" alt="Screen Shot 2019-07-12 at 09 49 13" src="https://user-images.githubusercontent.com/1378410/61098815-7eb8e780-a48a-11e9-9371-5975a1abfd21.png">

this is how i build my sitemap:
[sitemap link](https://amp.seword.com/sitemap-simple)

<img width="1523" alt="Screen Shot 2019-07-12 at 09 51 34" src="https://user-images.githubusercontent.com/1378410/61098871-ac9e2c00-a48a-11e9-8e07-7603a726f6d1.png">

**Comment by derduher** [comment]
@hbinduni This was fixed recently, update to the latest and your problem should be solved.
