### ISSUE TITLE
Is there a way to use it with a Vue project?

### ISSUE THREAD

**Issue by lelukas** [ekalinin/sitemap.js#218]
Hi, what would I have write in my vue.config.js in order for it to work? Can someone give me a working example?

**Comment by derduher** [comment]
I'm not familiar with Vue beyond it being a frontend framework. This library is not tied to any specific framework.  Does your site require a dynamic sitemap or do the amount of pages change infrequently?

**Comment by lelukas** [comment]
Vue provides a vue.config.js file  that is merged into webpack configuration file on build time. it has a file structure like this:
`
module.exports = {
  configureWebpack: {
     plugins:[]
   }
}
`

Should I put code inside plugins array?

**Comment by derduher** [comment]
There is no vue/webpack plugin that does this. You need a list of urls to pass to the library. I'm not sure if vue has a routes file. Any dynamic routes (passed a parameter/slug) would need to be explicitly passed to sitemap. You would then need to adapt its output to interface with webpack.
might be easier to just run after webpack as an explicit script.

**Comment by lelukas** [comment]
Yea, I thought about the possibility. Well, will do it. Thanks
