### ISSUE TITLE
GZipping files

### ISSUE THREAD

**Issue by elmarti** [ekalinin/sitemap.js#228]
The documented method for GZipping files breaks my TS compiler and doesn't appear to work when looking at the code. Has this been replaced with `toGzip()`? I may PR with a documentation update in a few days, but i'm still getting to grips with the package.

**Comment by elmarti** [comment]
Right, i appear to have misread the documentation, there is a `gzip` option on the `createSitemapIndex` documentation, which works perfectly, the point still stands about the lack of documentation, happy to create a PR unless i've missed anything?

**Comment by derduher** [comment]
PR welcome. I've just done a docs overhaul so I probably missed it.

**Comment by derduher** [comment]
Also feel free to drop any suggestions for improvement in here.

**Comment by derduher** [comment]
@elmarti I've added some docs but still feel free to open a PR for improvements.
