### ISSUE TITLE
pretty formating

### ISSUE THREAD

**Issue by cekvenich** [ekalinin/sitemap.js#229]
I think the sitemap XML generated used to be 'pretty' formatted. Now I just get a long string with no line spacing.

Do I have to use a XML beautifier?

**Comment by derduher** [comment]
I didn't think anyone wanted pretty print. I can add an option to a future version.

**Comment by derduher** [comment]
@cekvenich this is now in master. Call `smi.toString(true)` to get a pretty print form.

**Comment by cekvenich** [comment]
Great. But I have to wait for you to release it to npm, I have much complexity in my app.
