### ISSUE TITLE
Move CLI to its own package?

### ISSUE THREAD

**Issue by realityking** [ekalinin/sitemap.js#236]
It seems like the CLI and related functionality is adding more dependencies to sitemap. Many nom packages have gone ahead and split their CLI tools into a separate package to avoid adding unused dependencies to packages not using the CLI.

Would that be an option for sitemap.js?

**Comment by derduher** [comment]
I've thought about that. It'd probably end up moving the lib to another package just to preserve the ease of `npx sitemap`. And probably setting up an org. But to be honest the deps. are still fairly minimal at this point. I don't think we've quite reached the tipping point.
```
    "arg": "^4.1.1", <--- cli-only
    "sax": "^1.2.4", <--- shared
    "xmlbuilder": "^13.0.0" <-- hard dep for lib.
```
@realityking is there some specific problem you are trying to avoid?
