### ISSUE TITLE
Disable CDATA not working for non url. How to disable CDATA?

### ISSUE THREAD

**Issue by bdrtsky** [ekalinin/sitemap.js#245]
No matter what I try I ending up with 

```
<image:title><![CDATA[WOOOOOOOW]]></image:title>
```

Is there any way to get rid of CDATA?

**Comment by derduher** [comment]
@bdrtsky why do you want to? This field should generally be escaped to avoid encoding issues with characters that aren't allowed in xml.

**Comment by bdrtsky** [comment]
@derduher I made a research, looked at least at 30 huge content-oriented websites. None of them are using CDATA. Also I found a few forum topics how Google have issues with parsing content with CDATA:

https://github.com/Yoast/wpseo-news/issues/218
https://support.google.com/googlenews/forum/AAAAKvAM41ILjLGbgU_tZw/?hl=en&gpf=%23!topic%2Fnews%2FLjLGbgU_tZw

Also I found that few CMS'es removes CDATA support:
https://forge.typo3.org/issues/62374
http://get-simple.info/forums/showthread.php?tid=7375

**Comment by derduher** [comment]
Thanks for bringing this to my attention. I will try to switch from cdata to escaping as the next feature after the one I'm working on.

**Comment by bdrtsky** [comment]
Hey. I found first real-world usage example on big website - https://www.buzzfeed.com/animals.xml

I guess the best option would be an option to enable/disable CDATA when needed.

**Comment by derduher** [comment]
I'm planning on just escaping the xml to avoid having to support the option.

**Comment by Azraelless** [comment]
I'm having the same issue.

**Comment by derduher** [comment]
Just released this with v5, on master now, in npm shortly
