### ISSUE TITLE
[ BUG ] wrong lastmod W3C Datetime ISO8601 format

### ISSUE THREAD

**Issue by patrickmartin0** [ekalinin/sitemap.js#246]
**Description**
The supported datetime format for the lastmod tag ('2019-07-22T05:58:37.037Z') doesn't seem to actually be in ISO8601. Since the ISO8601 states: 

>    Year:
      YYYY (eg 1997)
   Year and month:
      YYYY-MM (eg 1997-07)
   Complete date:
      YYYY-MM-DD (eg 1997-07-16)
   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
   Complete date plus hours, minutes, seconds and a decimal fraction of a
second
      YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)

And when i pass a datetime format in the lastmod tag like this "2019-07-22T05:58+01:00" it always gets converted to something like "2019-07-22T05:58:37.037Z". I'm not quite sure if this is an actual bug or just some behaviour I don't understand.

**Expected behavior**
Passed lastmod datetime should not be converted.

**Desktop:**
 - Library Version [4.1.1]

**Comment by derduher** [comment]
@patrickmartin0 As documented in https://github.com/ekalinin/sitemap.js#sitemap-item-options we use the official w3c subset of ISO8601. Basically we take the date `(new Date('what you passed in')).toISOString()` This is a function of [javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString). Although there are libraries out there that preserve the full ISO8601, as this is supported natively and has no impact on the accuracy of the timestamp, this was consciously chosen. You do lose offset information but that isn't really relevant to crawlers. 
And just to be clear in the example you gave  `(new Date('2019-07-22T05:58+01:00')).toISOString()` converts out to `2019-07-22T04:58:00.000Z`. So the offset is accounted for.

**Comment by patrickmartin0** [comment]
Ah okay now I get it! thanks for your help!
