### ISSUE TITLE
[ BUG ] warning: failed to load external entity "./schema/all.xsd" S

### ISSUE THREAD

**Issue by damusix** [ekalinin/sitemap.js#254]
**Describe the bug**
Either a bug or bad error output for CLI tool

```
> npx sitemap --validate sitemap.xml 
warning: failed to load external entity "./schema/all.xsd"
Schemas parser error : Failed to locate the main schema resource at './schema/all.xsd'.
WXS schema ./schema/all.xsd failed to compile
```

Also, docs: https://github.com/ekalinin/sitemap.js#cli
Do not match code: https://github.com/ekalinin/sitemap.js/blob/master/cli.ts#L12

**Expected behavior**
Better error output or a functional CLI tool. Proper documentation.

**Desktop (please complete the following information):**
sitemap v5.0.0
node 10
osx mojave 10.14.5

**Additional context**
Context on docs: I have a feeling there was an undocumented API change because I've seen various things in the docs that don't match up with the code, eg: https://github.com/ekalinin/sitemap.js#example-of-most-of-the-options-you-can-use-for-sitemap (`streamToSitemap(smStream).then(console.log)`)

**Comment by derduher** [comment]
good catch on validate vs verify in the docs. I'll look into why its not loading all.xsd
And yeah v5 was released around a week ago so some docs have mistakes. Thanks and feel free to call out anything else that is either wrong or confusing.
