### ISSUE TITLE
I just want to use the date as the lastmod, I don't want to have time.

### ISSUE THREAD

**Issue by coldhurt** [ekalinin/sitemap.js#255]
I just want to use the date as the lastmod, I don't want to have time, 
but here is new Date().toISOString(), Is there any way for me to use only the date as lastmod?

**Comment by derduher** [comment]
Sorry, no, there is no way to pass the date without it converting to a full ISO date. This is done to simplify the code.
Why do you wish to pass only the date? Perhaps there is a usecase I am missing?

**Comment by coldhurt** [comment]
> Sorry, no, there is no way to pass the date without it converting to a full ISO date. This is done to simplify the code.
> Why do you wish to pass only the date? Perhaps there is a usecase I am missing?

Just product demand, because our search engine baidu is like this :(

**Comment by derduher** [comment]
Does baidu not accept or dislike full date + timestamp? I don't know too much about baidu.

**Comment by coldhurt** [comment]
> Does baidu not accept or dislike full date + timestamp? I don't know too much about baidu.

Its document shows only support date.

**Comment by derduher** [comment]
Alright, I will look into supporting this. Any links to documentation would appreciated, especially if they have a validator tool.
Please let me know if there are any other issues you run into using the maps generated with Baidu.

**Comment by coldhurt** [comment]
> Alright, I will look into supporting this. Any links to documentation would appreciated, especially if they have a validator tool.
> Please let me know if there are any other issues you run into using the maps generated with Baidu.

I found two official wikis, but only Chinese.
https://ziyuan.baidu.com/wiki/640
https://ziyuan.baidu.com/college/courseinfo?id=267&page=2#h2_article_title16
Sorry, i didn't find any validator tool.

**Comment by derduher** [comment]
Thank you. This is helpful. It looks like the mobile tag, which I recently dropped as google dropped it, is still required by baidu. I will try to add back support for that as well.
