### ISSUE TITLE
Error: Invalid character in string - how to sanitize data or gratefully fallback?

### ISSUE THREAD

**Issue by bdrtsky** [ekalinin/sitemap.js#264]
I noticed, that if string contains data, like `Some str\u0010ing` then `sitemap` completely freaks out and throws an error

```
Error: Invalid character in string: Some string at index 33
    at XMLStringifier.assertLegalChar (/home/.../node_modules/xmlbuilder/lib/XMLStringifier.js:208:19)
```

Tried to search a way how to sanitize the data (in xmlbuilder issues also) but have no luck. 
Is there any recommendations what to do in such cases? Any dedicated libs? I can't sanitize only a `\u0010` since there could be dozens of other symbols.

**Comment by derduher** [comment]
@bdrtsky can you paste a small sample so I may debug? reading the spec from the comments in xml builder it /should/ accept most utf8/16 unicode

**Comment by derduher** [comment]
It's possible bumping the xml version of the sitemap to 1.1 might help. If you wish to test for yourself you can reach into the source and tweak this line with 1.1. https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap-stream.ts#L12
