### ISSUE TITLE
Child_Process module not found

### ISSUE THREAD

**Issue by punitmirani30** [ekalinin/sitemap.js#269]
**[ error ] ./node_modules/sitemap/dist/lib/xmllint.js**
Module not found: Can't resolve 'child_process'  in /node_modules/sitemap/dist/lib'

Using sitemap as library gives above error

**Comment by derduher** [comment]
What version of node and the library are you using?

**Comment by punitmirani30** [comment]
Library version: 5.1.0
Node Version: 10.16.0

**Comment by derduher** [comment]
How are you running the library? are you trying to use it in the browser?

**Comment by punitmirani30** [comment]
Yes using it within browser.

**Comment by derduher** [comment]
@punitmirani30 child_process does not exist client side.
This library is not supported for use in the browser as that usecase does not make sense. When a search engine requests a sitemap it expects to get the already rendered xml in the response. This can be prerendered as a file stored to disk or generated at request-time serverside. It does not expect nor execute javascript/html if you send it to it.

**Comment by punitmirani30** [comment]
Okay so is there any way of using this library on client side ?? Or any suggestions from you.

**Comment by derduher** [comment]
Sorry no. Client side does not make sense for sitemaps. The server must do this. There is no way to do a sitemap clientside.

**Comment by derduher** [comment]
I would suggest you either set up an express server to generate this on request or have whoever handles the REST call do so.

**Comment by punitmirani30** [comment]
Okay. Thanks for the help.
