### ISSUE TITLE
Sitemap - API deprecated, Can't this be still be available as one more method as library

### ISSUE THREAD

**Issue by punitmirani30** [ekalinin/sitemap.js#270]
I am generating sitemap on the fly where getting list of urls and using sitemap deprecated api to create a sitemap and load it on the fly on url visit. Other options seems to be playaround with xml or physical sitemap file. 

API usage is simple and easy case in usecase when sitemap is to be generated on the fly

**Comment by derduher** [comment]
It is entirely replaced by newer methods, with examples you can see in the docs. The newer api methods also generate on the fly and at a smaller memory footprint. If you provide me some code of what you are trying to do in the deprecated API I can show you what that would be in the newer API.

**Comment by punitmirani30** [comment]
Here's is the code
const { Sitemap } = require('sitemap');
const sm = new Sitemap({
    urls: [{ url: '/path1' },{ url: '/path2' },{ url: '/path3' },{ url: '/path4' },{ url: '/path5' },{ url: '/path6' }],
    hostname: 'http://example.com',
})

Passing the sm.toString() to response as below

 res.write(sm.toString());
 res.end();

Which renders the xml sitemap

**Comment by derduher** [comment]
This code is the equivalent of that https://github.com/ekalinin/sitemap.js#example-of-using-sitemapjs-with-express
In the example it keeps the map in memory.

If you need to update it occasionally that is just a matter of busting the cache.

**Comment by punitmirani30** [comment]
The method you suggested seems mapping single single url using 
 smStream.write({ url: '/page-1/',  changefreq: 'daily', priority: 0.3 })
 smStream.write({ url: '/page-2/',  changefreq: 'monthly',  priority: 0.7 })
 
this method is fine but i am getting is list of urls from REST of (approx. 2000 urls this list can increase even more in future) and passing these set of urls array to API deprecated.

I am bit confused of how to use what you have suggested. doing something like this 
 smStream.write({ url: '/page-2/',  changefreq: 'monthly',  priority: 0.7 })

will be tricky and overhead

**Comment by derduher** [comment]
I am not exactly sure on which point you do not understand so I will try to explain. Apologies if I cover something you already know. See the comments in code.
```js
const express = require('express')
const { SitemapStream, streamToPromise } = require('sitemap')
const { createGzip } = require('zlib')

const app = express()
let sitemap
// For express on request to sitemap.xml execute the following code
app.get('/sitemap.xml', function(req, res) {
// Tell the search engine the content is xml
  res.header('Content-Type', 'application/xml');
// Tell the search engine we have compressed it
  res.header('Content-Encoding', 'gzip');
  // if we have a cached entry send it
  if (sitemap) {
    res.send(sitemap)
    return
  }
  try {
// This is roughly equivilant to `new Sitemap()`
    const smStream = new SitemapStream({ hostname: 'https://example.com/' })
// This takes the output from sitemap as we write to it and compresses it
    const pipeline = smStream.pipe(createGzip())
// Here we write each url individually
// you can do it one by one in code like this or in a loop from the REST call response
    smStream.write({ url: '/page-1/',  changefreq: 'daily', priority: 0.3 })
    smStream.write({ url: '/page-2/',  changefreq: 'monthly',  priority: 0.7 })
    smStream.write({ url: '/page-3/'})    // changefreq: 'weekly',  priority: 0.5
    smStream.write({ url: '/page-4/',   img: "http://urlTest.com" })
// REST varient
 restURLs.forEach((urlData) => {
smStream.write({url: urlData.path, changeFreq: urlData.freq})
}) 
//
// This tells the library that you have sent it all you plan to and to print out the xml end tag.
    smStream.end()

    // This saves the end result of the generated file to a variable so it doesn't need to be regenerated each time
    streamToPromise(pipeline).then(sm => sitemap = sm)
    // stream the response
    pipeline.pipe(res).on('error', (e) => {throw e})
  } catch (e) {
    console.error(e)
    res.status(500).end()
  }
})
// This just starts the server
app.listen(3000, () => {
  console.log('listening')
});
```

**Comment by punitmirani30** [comment]
Okay will give a try on this. Will update.

**Comment by derduher** [comment]
please reopen if there are further questions
