### ISSUE TITLE
lastmodDateOnly can be this be available irrespective of baidu, open for all case

### ISSUE THREAD

**Issue by punitmirani30** [ekalinin/sitemap.js#271]
Have a requirement where i need only date. So seems lastmodDateOnly can be helpful to everyone.

**Comment by derduher** [comment]
There is nothing stopping you from using the option for non-baidu search engines. It tells search engines less precise info though.

**Comment by punitmirani30** [comment]
So when i use the API deprecated method like below
I want something like this


const { Sitemap } = require('sitemap')
const sm = new Sitemap({
    urls: [{ url: '/path', lastmod:'2019-12-22',changefreq:'daily',priority:1, }],
    hostname: 'http://example.com',
    lastmodDateOnly: true
})
sm.toString()

when i am passing only date as lastmod key, i am getting 2019-12-22T00:00:00 where i don;t time to be displayed

**Comment by derduher** [comment]
This is the output I get when I run the above (line breaks inserted for readability)
```xml
<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url>
<loc>http://example.com/path</loc>
<lastmod>2019-12-22</lastmod>
<changefreq>daily</changefreq>
<priority>1.0</priority>
</url>
</urlset>
```
Which appears correct. I'm not sure how you are getting different.

**Comment by punitmirani30** [comment]
I will send some screenshots for your reference some time later.

**Comment by derduher** [comment]
Closing this for now. Please reopen if you need further assistance.
