### ISSUE TITLE
Opt-out xmlns

### ISSUE THREAD

**Issue by bdrtsky** [ekalinin/sitemap.js#272]
I don't think this is a good idea to give Google sitemaps with "news" xmlns, while it is not. I don't see any way to remove unnecessary xmlns. I saw old issue but this is not working now - https://github.com/ekalinin/sitemap.js/issues/149

**Comment by derduher** [comment]
Hi @bdrtsky any particular reason you would like it to not be there?

**Comment by bdrtsky** [comment]
@derduher right now Sitemap Submit is working awful in new Search Console. So many random errors (I found hundreds of topics on Google Webmasters Forum). So I am trying any potential solutions that can help in this situation. My logic is following.

News sitemaps has very strict requirements - https://support.google.com/news/publisher-center/answer/9606710

The only way for Google to distinguish between News sitemap and non-news sitemap is looking for this namespace, right? In that case it will mark (or I should say `could mark` - because nobody knows what is happening in new Search Console with this awful new Sitemaps submission) such sitemap as non-valid, since it's doesn't meet News Sitemap requirements.

**Comment by derduher** [comment]
@bdrtsky That seems like a good enough reason. I'll add it to the queue.

**Comment by derduher** [comment]
@bdrtsky See #274 PR for implementation. Feel free to request tweaks. I'll try and cut a release in the next week or two.

**Comment by bdrtsky** [comment]
Looks good! Appreciate your efforts 👍
