### ISSUE TITLE
[ BUG ] XSL

### ISSUE THREAD

**Issue by arpowers** [ekalinin/sitemap.js#275]
Does this library have any way to add an XSL file? The sole documented option doesn't work.

**Comment by derduher** [comment]
@arpowers It was removed in the previous release. Why do you want to style a sitemap xml file?

**Comment by arpowers** [comment]
To make it more human-readable which is needed to review it for accuracy and optimization.  

It's not something that needs to be specifically supported, but it would be trivial to add an option that allows arbitrary XML headers to be added, etc..

**Comment by arpowers** [comment]
The issue on my end that brought me to this is here: 
https://github.com/fiction-com/factor/issues/129

**Comment by derduher** [comment]
I'll take a look again at the code to see why I removed it. I may have simply underestimated its usage.

**Comment by arpowers** [comment]
Thank you!
-- 
Founder @ Fiction.com

**Comment by arpowers** [comment]
Update on this?

**Comment by derduher** [comment]
@arpowers sorry was holding off until the 6.0.0 release was fully out. Try `npm install --save ekalinin/sitemap.js#next` with `xslUrl: "https://example.com/style.xsl"`  as an option to either sitemapstream, sitemapindex or createsitemapandindex. 

I'll throw together some docs and do a real release when I next get the chance if that looks good.

**Comment by arpowers** [comment]
@derduher thanks for adding that,  you may want to consider just adding a vanilla XML headers option which may support more use cases.  Other than that, I'm happy as long as I can create a nice looking sitemap :P

**Comment by derduher** [comment]
published in 6.1.0
