### ISSUE TITLE
<How to update existing sitemap>

### ISSUE THREAD

**Issue by gate3** [ekalinin/sitemap.js#277]
I can create a sitemap and can read the data from it. However, I need to be able to add to what I have read from a sitemap and save back to file. Here is what I have tried, 

```
const xm = await parseSitemap(createReadStream(fileName))
for (const m of merch) {
        xm.push({ url: `@${m}`, changefreq: 'daily', priority: 0.3 })
}
createSitemap(xmlConfig)
```
Nothing gets written back to file. Any help in making this work will be appreciated. Thanks

**Comment by derduher** [comment]
Hi @gate3 try this example https://github.com/ekalinin/sitemap.js/blob/master/examples/append.js

**Comment by derduher** [comment]
Please reopen if that example did not solve your issue.
