### ISSUE TITLE
[Feature] Sitemap management. 

### ISSUE THREAD

**Issue by RayLuxembourg** [ekalinin/sitemap.js#279]
**Is your feature request related to a problem? Please describe.**
The current documentation does not explain how to maintain the sitemap.
An example is, the first time I generate the sitemap, I query 23k documents from MongoDB and each represents a page in my application. Those pages have been updated here and there and every time they do, I should be able to update the sitemap as well without touching the whole sitemap.

**Describe the solution you'd like**
Create a sitemap once and save it as a file. Allow adding and updating a <URL> with all of its options. 

**Additional context**
If this is possible using the current API then please point me to the correct documentation or an example.

**Comment by derduher** [comment]
@RayLuxembourg for adding https://github.com/ekalinin/sitemap.js/blob/master/examples/append.js gives an example. You can replace process.stdin with a fscreateReadStream('./path/to/existingmap.xml'). call smStream.write() on each addition from the db.

As for updating, you may be able to use the same XMLToISitemapOptions (soon to be XMLToSitemapOptions) to parse the existing sitemap and write a Transform that will update entries as they come through. 
I'll try and write up a more direct example for these.

As a heads up 6.0 was merged to master yesterday but has yet to be released on npm. That should hopefully happen shortly. For now the docs on npm reflect what is actually published.

Thanks for creating the issue!

**Comment by derduher** [comment]
Append.js has been updated to have a more direct example of updating a sitemap with additions and updates. I realize this is perhaps more code than the average user unfamiliar with streams would want to write so I plan to create a wrapper at some point in the future. 
In the meantime please reopen this issue if you have any questions.

**Comment by rnicholls** [comment]
I have the same ask as OP @derduher but the https://github.com/ekalinin/sitemap.js/blob/master/examples/append.js gives me a 404.

**Comment by rnicholls** [comment]
Nevermind. I see that update is the file that has the example now. Unfortunately it won't work with my use case. I have 100s of thousands of pages, so it doesn't look like it can split it across multiple sitemaps and then append.
