### ISSUE TITLE
Sitemap can't be used with browserify 

### ISSUE THREAD

**Issue by pquerna** [ekalinin/sitemap.js#28]
If sitemap.js is pulled into a [browserify](https://github.com/substack/node-browserify) build, the javascript has frontend errors, because the use of fs.readFileSync to get the version number is done in a way that [brfs](https://github.com/substack/brfs) can't understand:

``` js
/**
 * Framework version.
 */
var fs = require('fs')
  , path = require('path')
  , pack_file = path.join(__dirname, 'package.json');

if ( !module.exports.version ) {
  module.exports.version = JSON.parse(
    fs.readFileSync(pack_file, 'utf8')).version;
}
```

If this was changed to be something like:

``` js
var fs = require('fs');

if ( !module.exports.version ) {
  module.exports.version = JSON.parse(
    fs.readFileSync(__dirname + "/package.json", 'utf8')).version;
}
```

It should work with brfs

**Comment by pquerna** [comment]
(yes, I admit that sitemap.js being pulled into a browserify build probably means something else has gone wrong)

**Comment by alexeybondarenko** [comment]
+1

**Comment by AhmedAbdulrahman** [comment]
@alexeybondarenko can you give us an example how do use both together, I am trying to make a dynamic sitemap using `sitemap.js` and `react-router-sitemap`. I want to get my react routes dynamically :)
