### ISSUE TITLE
[Feature] Save sitemap as sitemap.xml

### ISSUE THREAD

**Issue by jfoclpf** [ekalinin/sitemap.js#281]
Can you give just a simple example of saving the sitemap to a file?
I sa the [examples directory](https://github.com/ekalinin/sitemap.js/tree/master/examples) and saw none. I must confess I found the examples provided on readme, regarding the stream, quite complex.

I tried this:
```js
const fs = require('fs')
const { SitemapStream, streamToPromise } = require('sitemap')
// Creates a sitemap object given the input configuration with URLs
const sitemap = new SitemapStream({ hostname: 'http://example.com' });
sitemap.write({ url: '/page-1/', changefreq: 'daily', priority: 0.3 })
sitemap.write('/page-2')
sitemap.end()
 
streamToPromise(sitemap)
  .then(sm => {
      fs.writeFile(path.join('public', `sitemap.xml`), sm.toString(), function (err) {
        if (err) {
          console.error(err)
        } else {
          console.log(`File generated: sitemap.xml`)
        }
      })
   })
  .catch(console.error);
```
This approach though takes ages! I think I should pass the stream, right?

**Comment by jfoclpf** [comment]
ok go it, you may close the issue :) but please consider to add this as example, cause the [stream example](https://www.npmjs.com/package/sitemap#stream-writing-a-sitemap) you have there is a bit messy, if I may say :) 

```js
const fs = require('fs')
const { SitemapStream } = require('sitemap')
const sitemap = new SitemapStream({ hostname: 'http://example.com' });

var writeStream = fs.createWriteStream('sitemap.xml')
smStream.pipe(writeStream)

sitemap.write({ url: '/page-1/', changefreq: 'daily', priority: 0.3 })
sitemap.write('/page-2')
sitemap.end()
```

All the best and thanks for the package

**Comment by derduher** [comment]
@jfoclpf Thanks for the feedback. Can I ask were you trying to write to file for a single operation or for put together a script to be run on batch? 

I'm thinking about re-organizing the docs around a couple use-cases. 
- one time use -> push them to the cli
- on-going server updates
- library integration

Thanks again!

**Comment by derduher** [comment]
Docs have been reorganized, your input is welcome.

**Comment by jfoclpf** [comment]
Hi, thanks for the reply. It's for a single operation to be run when the server starts. I save all sitemaps into directory public/
I saw your example of express but I prefer to save them to files to save memory cause I have a huge list of sitemaps.
