### ISSUE TITLE
[ BUG ] TypeError: buildSitemapIndex is not a function

### ISSUE THREAD

**Issue by jfoclpf** [ekalinin/sitemap.js#283]
**Describe the bug**
I copied-paste exactly [this piece of code](https://www.npmjs.com/package/sitemap#building-just-the-sitemap-index-file) taken from readme

```js
const { buildSitemapIndex } = require('sitemap')
const smi = buildSitemapIndex({
  urls: ['https://example.com/sitemap1.xml', 'https://example.com/sitemap2.xml'],
  xslUrl: 'https://example.com/style.xsl' // optional
})
```

**Expected behavior**
It should have allowed to generate some stream to save sitemap index to a file

**Context:**
 - Library Version, "sitemap": "6.0.0"

**Error**

```
TypeError: buildSitemapIndex is not a function
    at renderSitemapIndex (/home/jfolpf/delp.pt/js/sitemap.js:84:15)
    at /home/jfolpf/delp.pt/js/sitemap.js:44:5
    at /home/jfolpf/delp.pt/node_modules/words-pt/index.js:69:9
    at /home/jfolpf/delp.pt/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/jfolpf/delp.pt/node_modules/async/dist/async.js:268:20)
    at replenish (/home/jfolpf/delp.pt/node_modules/async/dist/async.js:435:29)
    at iterateeCallback (/home/jfolpf/delp.pt/node_modules/async/dist/async.js:424:21)
    at /home/jfolpf/delp.pt/node_modules/async/dist/async.js:321:20
    at /home/jfolpf/delp.pt/node_modules/async/dist/async.js:2953:17
    at /home/jfolpf/delp.pt/node_modules/words-pt/index.js:54:13
```
I also tried with `new` but it's not either a constructor

**Comment by jfoclpf** [comment]
got it again ;) 

I used the other example: https://www.npmjs.com/package/sitemap#sitemapindexstream

```js
const smis = new SitemapIndexStream({ level: 'warn' })
smis.write({ url: 'https://example.com/' })
smis.write({ url: 'https://example.com/2' })

var writeStream = fs.createWriteStream('sitemap.xml')
smis.pipe(writeStream)

writeStream.on('error', (err) => {
  console.error(Error(err))
})

smis.end()
```

As I said, that readme is a bit chaotic. You may close the issue :)
Anyway, thanks for the package

**Comment by derduher** [comment]
I'll take another look at those examples and correct them. Thanks for opening bugs. It really helps me help others.

Any suggestions to make the docs I've recently updated less chaotic? (minus this one here as I haven't gotten to it yet.)

**Comment by jfoclpf** [comment]
The docs are much better now, thanks. Just let me report you another
apparent bug. I'm with the phone now and I can't add code here, but I am
using that example of saving the sitemap to a file using the stream. With
some tests I have made with a sitemap with more than 400 urls, the file is
not fully saved, that is, only the first 300 urls are saved and the the tag
urlset is not closed at the end of the file.

**Comment by derduher** [comment]
Sounds like it threw an error. Check stderr.

**Comment by derduher** [comment]
Please reopen if you are still experiencing the additional issue you reported above. If possible include any error messages or the urls themselves.
