### ISSUE TITLE
[ BUG ] createSitemap. getting a Module has no exported member

### ISSUE THREAD

**Issue by gdubs** [ekalinin/sitemap.js#285]
**Describe the bug**
I have a lerna project with a sitemap package and when I build the project it would throw an error whenever I call createSitemap.

`Module '"../../../../node_modules/sitemap/dist"' has no exported member 'createSitemap'`

It would do the same with buildSitemapIndex as well

`Module '"../../../../node_modules/sitemap/dist"' has no exported member 'buildSitemapIndex'.`

I went in and looked at index.js and I dont see createSitemap on the exports, only parseSitemap and createSitemapIndexStream (which is depecrated as per documentation). 

Any advice what I need to do to fix the issue or what to look for?

**Context:**
 - 6.1.0

**Comment by derduher** [comment]
createSitemap and buildSitemapIndex were removed in 6.0. They were deprecated in 5.x. You'll want to see the examples for the more optimized streaming interface introduced in 5.x. Feel free to ask questions if the examples are unclear, inaccurate or do not fit your usecase. Closing.
