### ISSUE TITLE
[ BUG ] Missing </sitemapindex> tag when using createSitemapsAndIndex

### ISSUE THREAD

**Issue by thathurtabit** [ekalinin/sitemap.js#286]
**Describe the bug**
Using `createSitemapsAndIndex` generates an `xml` file, but seems to be missing the closing `</sitemapindex>` tag, causing `xml` to be invalid.

**Expected behavior**
```
createSitemapsAndIndex({
    hostname: URL,
    targetFolder: TARGET_FOLDER,
    gzip: false,
    sitemapName: 'sitemap',
    urls: [...],
});
```
Should generate:
```
<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>https://fretmap.app/sitemap-0.xml</loc></sitemap></sitemapindex>
```
But instead generates the above, without the closing `</sitemapindex>`

**Context:**
 - Library Version `"sitemap": "^6.1.0",`

**Additional context**
Great work though!

**Comment by ruiwei** [comment]
Chrome error: "error on line 1 at column 179: Extra content at the end of the document".
/lib/sitemap-index-stream.ts 
Line 75: looks like this did not call

**Comment by derduher** [comment]
This has been patched and released. Pleased be advised createSitemapsAndIndex is deprecated and will be removed in the next major version. I recommend moving to SitemapAndIndexStream https://github.com/ekalinin/sitemap.js/blob/master/api.md#sitemapandindexstream. Please feel free to open a ticket if documentation is not clear.
