### ISSUE TITLE
Interface access to XML file presentation issues

### ISSUE THREAD

**Issue by wenbinobject** [ekalinin/sitemap.js#288]
**Describe the bug**

  if (xhtml) {
    ns += ' xmlns:xhtml="http://www.w3.org/1999/xhtml"';
  }
 I had a format problem with browser access
![image](https://user-images.githubusercontent.com/21998076/79207029-be29bf80-7e72-11ea-948d-9098a4931ba7.png)

 If I  http modify https
  if (xhtml) {
    ns += ' xmlns:xhtml="https://www.w3.org/1999/xhtml"';
  }
Is no problem

![image](https://user-images.githubusercontent.com/21998076/79207082-d0a3f900-7e72-11ea-8d97-88ea0b275177.png)

**Expected behavior**

I want to open it in the browser to view it correctly
my website
https://www.balletcrypto.com/sitemap.xml

**Context:**
 - Library Version "sitemap": "^6.1.1",

Demand

const defaultXMLNS: NSArgs = {
  news: true,
  xhtml: true,
  image: true,
  video: true,
  xhtmlUrl:"http://www.w3.org/1999/xhtml"
};
export interface NSArgs {
  news: boolean;
  video: boolean;
  xhtml: boolean;
  image: boolean;
  xhtmlUrl:string;
  custom?: string[];
}

const smStream = new SitemapStream({
  hostname: 'http://www.balletcrypto.com,
  lastmodDateOnly: false, // print date not time
  xmlns: { // trim the xml namespace
    news: true, // flip to false to omit the xml namespace for news
    xhtml: true,
    image: true,
    video: true,
    xhtmlUrl: "https://www.w3.org/1999/xhtml",
  }
 })

**Comment by derduher** [comment]
SitemapStream and SitemapIndexStream both have an undocumented option xslUrl that you can use to style your xml however you like. https://www.w3schools.com/xml/xsl_languages.asp
