### ISSUE TITLE
Is there a way to pass an array of urls to lineSeparatedURLsToSitemapOptions?

### ISSUE THREAD

**Issue by omar-dulaimi** [ekalinin/sitemap.js#289]
I'm trying to create a multipart xml sitemap, the example in the docs shows that it has to be read from a txt file. However I don't have access to the filesystem where I want to do this.

Any idea?
thanks!

**Comment by omar-dulaimi** [comment]
Nevermind, I found out how.

**Comment by bonesoul** [comment]
@omar-dulaimi same issue here, can you send your sample usage please?

**Comment by justColbs** [comment]
@omar-dulaimi  I'm also looking for how you figured this out. Please share your solution. Thanks!
