### ISSUE TITLE
XML Parsing Error: no root element found when using img array

### ISSUE THREAD

**Issue by knoxcard2** [ekalinin/sitemap.js#291]
I am getting the following error when I add the img array attribute...

**XML Parsing Error: no root element found
Location: https://www.buycanna.io/sitemap-index.xml
Line Number 1, Column 373:**

```
var entry = {
	url: url,
	changefreq: 'daily',
	priority: 0.8,
	lastmod: require('dayjs')().format('YYYY-MM-DD'),
	links: [{
		lang: 'en',
    	url: url,
    }],
    img: []
}
// console.log(url)
disp_urls.push(entry)
if(curr.menu_categories) {
	curr.menu_categories.forEach(category => {
		var cat_url = [
			url,
			category.slug,
		].join('/')
		// console.log(cat_url)
		entry.url = cat_url
		entry.links[0].url = cat_url
		if(curr.menu_items[category.slug]) {
			if(curr.menu_items[category.slug].length) {
				var img = []
				curr.menu_items[category.slug].forEach(item => {
					entry.img.push({
						url: 'https://www.yahoo.com/1.jpg',
						caption: 'test',
						title: 'test'
					})
				})
				entry.img = img
			}
		}
		disp_urls.push(entry)
	})
}
```

**Comment by knoxcard2** [comment]
Looks like I solved this, needs to be `imgs`, not `img`.  The documentation README.md is incorrect.  Submitted pull request.

**Comment by knoxcard2** [comment]
This is definitely an issue.  Cannot include images into my sitemap.

**Comment by knoxcard2** [comment]
This has been resolved.  I had this code running inside a gulpfile and the code was exiting too early by calling `deferred.resolve()` right after 
```
const {
				createSitemapsAndIndex
			} = require('sitemap')
			createSitemapsAndIndex(
```
which does not have a callback

```
const Q = require('Q')
const deferred = Q.defer()
deferred.resolve()
return deferred.promise
```

**Comment by derduher** [comment]
createSitemapsAndIndex is an async function so it returns a promise. You can wait until that promise resolves. I would however recommend switching to SitemapAndIndexStream as createSitemapsAndIndex is deprecated and will be removed in the next major version.
