### ISSUE TITLE
createSitemapsAndIndex deprecated <- What's the recommended way to auto generate a sitemap + index file in one go?

### ISSUE THREAD

**Issue by AdityaAnand1** [ekalinin/sitemap.js#294]
Found this old version of the readme:
https://github.com/ekalinin/sitemap.js/tree/ed82abb182c717116be71f8323919c45233519d1#auto-creating-sitemap-and-index-files-from-one-large-list

The mentioned method `createSitemapsAndIndex()` seems to be deprecated now, I couldn't find any mention of a replacement.

What's the recommended way to create a sitemap index file along with gzipped sitemaps from one long list of URLs?

**Comment by AdityaAnand1** [comment]
The deprecated method seems to work brilliantly by the way, I wonder why it was removed?

```
const smi = sitemap.createSitemapsAndIndex({
  hostname: 'http://www.sitemap.org',
  sitemapName: 'sitemap',
  sitemapSize: 2,
  targetFolder: 'build',
  urls: ['http://ya.ru', 'http://ya2.ru']
});
```

This is exactly what I wanted
![image](https://user-images.githubusercontent.com/13274079/81505516-69f8ea80-930d-11ea-80ac-d2ca2011577a.png)

But what does the future hold for `createSitemapsAndIndex()`? Why was it deprecated and what's the best alternative?

**Comment by derduher** [comment]
@AdityaAnand1 The recommended replacement is here https://github.com/ekalinin/sitemap.js#create-sitemap-and-index-files-from-one-large-list. createSitemapsAndIndex was deprecated as it required you to provide all the URLs up front. The newer method allows a streaming OR all at once  of the URLs. Internally it was already using the streaming interface linked above.
