### ISSUE TITLE
[Feature] links tag not support Google sitemap format

### ISSUE THREAD

**Issue by tedshd** [ekalinin/sitemap.js#296]
I find that use `links` generate format not support Google localized sitemap XML format

https://support.google.com/webmasters/answer/189077?hl=en

Sitemap for Google is `xhtml:link `

**Comment by derduher** [comment]
They should be generating exactly what is shown in the link. `smis.write({url: 'https://example.com', img: [], video: [], links: [{url: "http://www.example.com/deutsch/page.html", "lang": "de"]})`

**Comment by tedshd** [comment]
Get it.
Thank a lot.

**Comment by Thayakaran** [comment]
still, I'm getting link tag, but google mentioned **xhtml:link**. what should I do?

**Comment by Floriferous** [comment]
We're having the same issue, google's docs are very specific about this, how can we get the exact same output?

https://developers.google.com/search/docs/advanced/crawling/localized-versions#example_2
