### ISSUE TITLE
Stale files in published packages?

### ISSUE THREAD

**Issue by NathanHowell** [ekalinin/sitemap.js#298]
It appears that some old files (from 5.x?) are being published in 6.1.3, see https://cdn.jsdelivr.net/npm/sitemap@6.1.3/dist/lib/sitemap.js

I don't see this file created if I build locally, and it references dependencies that are no longer used such as `xmlbuilder`:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable camelcase, semi */
/*!
 * Sitemap
 * Copyright(c) 2011 Eugene Kalinin
 * MIT Licensed
 */
const xmlbuilder_1 = require("xmlbuilder");
const sitemap_item_1 = require("./sitemap-item");
const types_1 = require("./types");
const zlib_1 = require("zlib");
const url_1 = require("url");
const fs_1 = require("fs");
const utils_1 = require("./utils");
const sitemap_stream_1 = require("./sitemap-stream");
function boolToYESNO(bool) {
    if (bool === undefined) {
        return bool;
    }
    if (typeof bool === 'boolean') {
        return bool ? types_1.EnumYesNo.yes : types_1.EnumYesNo.no;
    }
    return bool;
}
```

**Comment by derduher** [comment]
weird. I'll take a look after I get done with my day job.

**Comment by NathanHowell** [comment]
👍 I was upgrading some code and ran into this. If I remove the references to the legacy modules everything seems to work fine, possibly just need to add a `git clean -xfd` type of action to the publishing script?
