### ISSUE TITLE
Is there a way to pass an array of objects to lineSeparatedURLsToSitemapOptions? 

### ISSUE THREAD

**Issue by justColbs** [ekalinin/sitemap.js#304]
I need to use the SitemapAndIndexStream index function you provided in the example. How can I just pass in an array of objects to be generated into XML instead of JSON in a txt file? 

This is more for convenience so I could skip the step of converting all my objects to JSON and inserting in a txt file.

I hope i'm posting this in the correct place. Thanks!

**Comment by derduher** [comment]
I'm assuming you are talking about [this example](https://github.com/ekalinin/sitemap.js#create-sitemap-and-index-files-from-one-large-list).
```lineSeparatedURLsToSitemapOptions(
  createReadStream('./your-data.json.txt')
)
.pipe(sms)
.pipe(createGzip())
.pipe(createWriteStream(resolve('./sitemap-index.xml.gz')));```

If you are just looking to take an array staticaly defined int the code, instead of lineSeparatedUrls
```
sms
.pipe(createGzip())
.pipe(createWriteStream(resolve('./sitemap-index.xml.gz')));
const arrayOfObjects = [ {...}, ...]
arrayOfObjects.forEach(item => sm.write(item))
```

**Comment by juspky** [comment]
It would be helpful to add this to the readme, as I found myself wondering about that aswell.

**Comment by derduher** [comment]
[It kind of does](https://github.com/ekalinin/sitemap.js/blob/master/README.md#generate-a-one-time-sitemap-from-a-list-of-urls) but I'll see what I can do to make that stand out a bit more.

**Comment by justColbs** [comment]
> ```js
> sms
> .pipe(createGzip())
> .pipe(createWriteStream(resolve('./sitemap-index.xml.gz')));
> const arrayOfObjects = [ {...}, ...]
> arrayOfObjects.forEach(item => sm.write(item))
> ```

That's it! Thank you. I would add that I had to change `sm.write(item)` to `sms.write(item)` and I had to call `sms.end()` once I wrote all my items in order to initiate the save (I assume that's the purpose).
