### ISSUE TITLE
[ BUG ] Problem with tsc compiling when using sitemap package

### ISSUE THREAD

**Issue by fr1sk** [ekalinin/sitemap.js#305]
**Describe the bug**
I am using `sitemap` with Nest.js and when I try to compile using `tsc` I got those errors:
```
node_modules/sitemap/dist/lib/sitemap-index-stream.d.ts(2,39): error TS2305: Module '"stream"' has no exported member 'TransformCallback'.
node_modules/sitemap/dist/lib/sitemap-item-stream.d.ts(2,39): error TS2305: Module '"stream"' has no exported member 'TransformCallback'.
node_modules/sitemap/dist/lib/sitemap-parser.d.ts(3,49): error TS2305: Module '"stream"' has no exported member 'TransformCallback'.
node_modules/sitemap/dist/lib/sitemap-stream.d.ts(2,39): error TS2305: Module '"stream"' has no exported member 'TransformCallback'.
```
Any clue why is this happening? I just tried with the example provided in the readme file, nothing super fancy. Thanks in advance ✌🏻

**Expected behavior**
To compile without errors.

**Context:**
 - Library Version: 6.1.4
 - Node version: 12.13.0
 - Typescript version: 3.7.5

**Additional context**
/

**Comment by derduher** [comment]
@fr1sk could you either share a minimal reproducible sample or specify which example you are using? I have not been able to reproduce the issue.

**Comment by fr1sk** [comment]
@derduher The problem was on my side, I had mismatched versions between `node`, and `@types/node`. After upgrading `@types/node` the error was gone. This has nothing to do with your library, so I will close the issue :)
