### ISSUE TITLE
How to pass options to lineSeparatedURLsToSitemapOptions method ? 

### ISSUE THREAD

**Issue by gokhancetiner** [ekalinin/sitemap.js#309]
I mean I couldn't add changefreq, priority vs options to generated sitemap. Is there any way to add these options on sitemap that generated witj lineSeparatedURLsToSitemapOptions method ?

Many Thanks

**Comment by derduher** [comment]
@gokhancetiner Here is [example file](https://github.com/ekalinin/sitemap.js/blob/master/tests/mocks/cli-urls.json.txt) input that allows you to pass in the options.
It will autodetect whether you are passing in JSON or just plain URLS

**Comment by gokhancetiner** [comment]
I haven't tried yet but thank you for quick reply @derduher
