### ISSUE TITLE
what is the correct format of json object to prepend list of URL's  from a json file

### ISSUE THREAD

**Issue by mininduhewawasam** [ekalinin/sitemap.js#310]
I tried it as below but it did not work

[
    {
        "url": "http://test.com/page-1/",
        "image": [
            {
            "url": "http://test.com/img1.jpg",
            "caption": "An image",
            "title": "The Title of Image One",
            "geoLocation": "London, United Kingdom",
            "license": "https://creativecommons.org/licenses/by/4.0/"
            }
        ],
        "video": [
            {
            "thumbnail_loc": "http://test.com/tmbn1.jpg",
            "title": "A video title",
            "description": "This is a video"
            }
        ],
        "links": [
            { 
                "lang": "en",
                "url": "http://test.com/page-1/"
            }
        ],
        "androidLink": "android-app://com.company.test/page-1/",
        "news": {
            "publication": {
            "name": "The Example Times",
            "language": "en"
            },
            "genres": "PressRelease",
            "publication_date": "2008-12-23",
            "title": "Companies A, B in Merger Talks",
            "keywords": "business, merger, acquisition, A, B",
            "stock_tickers": "NASDAQ:A, NASDAQ:B"
        }
    }
]

**Comment by derduher** [comment]
@mininduhewawasam  Here is example file input that allows you to pass in the options.
It will autodetect whether you are passing in JSON or just plain URLS.
Note each entry is on a single line.

**Comment by mininduhewawasam** [comment]
@derduher Thanks a lot solved the problem
