### ISSUE TITLE
[question] Maintain multiple sitemaps dynamicly

### ISSUE THREAD

**Issue by ozkanonur** [ekalinin/sitemap.js#312]
I have a dynamic routes that depends to API response. My scenario is an example when I open example.com/example-slug on SSR part, when this slug responses 200 from API then I write it to sitemap. I have tried SitemapAndIndexStream, but it doesnt really work like expected. It resets index to 0 everytime when I route to a page. And instead of updating existing sitemap, it removes everything in it with putting the current url. I couldnt see example that fits in my scenario. I want to update last indexed sitemap with routed page. It would be great if you show me the way to do it.

**Comment by derduher** [comment]
SitemapAndIndexStream really is intended to be run once. For dynamic updates on multiple sitemaps you will have to combine several approaches. 
[Parse](https://github.com/ekalinin/sitemap.js/blob/master/api.md#XMLToSitemapItemStream) an existing sitemap, presumably the last non-filled one and then feed it back in to the sitemap generator with the addition of your new entries. [here] is an example from the CLI that prepends to an existing sitemap by feeding in a new file of entries, you don't have to use the file you can just write directly to the stream to prepend. 
There is a lot of discussion on this algorithm here https://github.com/ekalinin/sitemap.js/issues/258

**Comment by ozkanonur** [comment]
I used packages called xml-js and glob to overcome this. The 'here' link is not linked properly so I cant see the example. If you wonder how I overcome on that, [here](https://github.com/feednext/feednext/blob/master/server/src/shared/Services/sitemap.manipulation.service.ts) is my solution that works crystal clear on production. @derduher

**Comment by derduher** [comment]
Glad you were able to figure something out. I'll try and create an example for what you are describing in the future. Also I edited my broken link, sorry about that.
