### ISSUE TITLE
Allow use of allow_embed in VideoItem API

### ISSUE THREAD

**Issue by hhimanshu** [ekalinin/sitemap.js#314]
**Is your feature request related to a problem? Please describe.**
Currently [VideoItem API](https://github.com/ekalinin/sitemap.js/blob/master/api.md#videoitem) does not support `allow_embed` option in `player_loc`.

It is available in [Google Documentation](https://support.google.com/webmasters/answer/80471?hl=en). Search for `allow_embed` to find it

**Describe the solution you'd like**
Allow the users to use this option through `VideoItem` API

**Additional context**

**Comment by derduher** [comment]
Thanks for catching that. This has been implemented in 6.1.6

**Comment by hhimanshu** [comment]
Thanks for the change!
