### ISSUE TITLE
[question] How to create some sitemaps?

### ISSUE THREAD

**Issue by coolswood** [ekalinin/sitemap.js#316]
I try to use example `sitemapAndIndexStream `. My code:
```js
const sms = new SitemapAndIndexStream({
  limit: 10000,
  getSitemapStream: (i) => {
    const sitemapStream = new SitemapStream();
    const path = `./sitemap-${i}.xml`;

    sitemapStream
      .pipe(createWriteStream(resolve(path))); // write it to sitemap-NUMBER.xml

    return [new URL(path, 'https://example.com/subdir/').toString(), sitemapStream];
  },
});

sms
  .pipe(createWriteStream(resolve('./sitemap-index.xml')));

const arrayOfSitemapItems = [{ url: '/page-1/', changefreq: 'daily'}, { url: '/page-2/', changefreq: 'daily'}];
arrayOfSitemapItems.forEach(item => sms.write(item));
```

But I have an error `TypeError [ERR_INVALID_URL]: Invalid URL: /page-1/`

**Comment by derduher** [comment]
@coolswood Thanks for pointing that out. I've updated the documentation to reflect that you should pass in a hostname to the sitemapStream on creation if you want it to resolve relative paths. Alternatively you can directly pass full URLs.

**Comment by derduher** [comment]
[here's](https://github.com/ekalinin/sitemap.js/commit/d397a1546f2564d5d2031e1bb5d64b30d4b4eb0e#diff-04c6e90faac2675aa89e2176d2eec7d8L124) a direct link to what you need to change

**Comment by coolswood** [comment]
Thank you, it works!
