### ISSUE TITLE
[ BUG ] TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by waleedarshad-vf** [ekalinin/sitemap.js#317]
Got this error while calling:     `streamToPromise(sms).then(buffer => console.log(buffer.toString()))`

TypeError [ERR_INVALID_ARG_TYPE]: The "list" argument must be one of type Array, Buffer, or Uint8Array. Received type undefined

**Comment by waleedarshad-vf** [comment]
stack

```
buffer.js:458
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "list" argument must be one of type Array, Buffer, or Uint8Array. Received type undefined
    at Function.concat (buffer.js:458:11)
    at Writable.stream.pipe.on.on (/Users/macbookpro/Documents/eFuse_BE/node_modules/sitemap/dist/lib/sitemap-stream.js:103:48)
    at Writable.emit (events.js:203:15)
    at Writable.EventEmitter.emit (domain.js:448:20)
    at finishMaybe (_stream_writable.js:646:14)
    at endWritable (_stream_writable.js:663:3)
    at Writable.end (_stream_writable.js:594:5)
    at SitemapAndIndexStream.onend (_stream_readable.js:671:10)
    at Object.onceWrapper (events.js:286:20)
    at SitemapAndIndexStream.emit (events.js:203:15)
```

**Comment by derduher** [comment]
Hi @waleedarshad-vf, just giving you a heads-up that I will look into this this weekend. Not ignoring you, just busy hunting for a new job.

**Comment by waleedarshad-vf** [comment]
Thanks

**Comment by derduher** [comment]
@waleedarshad-vf I'm going to need more than a stacktrace to debug this. Please provide a minimal reproducible test case and the version of node you are on.

**Comment by waleedarshad-vf** [comment]
@derduher 
Node: v10.16.3

I just followed simple steps

```
  const sms = new SitemapAndIndexStream({
    limit: 10000, // defaults to 45k,  it will create a new sitemap file based upon limit
    getSitemapStream: i => {
      const sitemapStream = new SitemapStream({
        hostname: domain
      });
      const path = `./sitemap/sitemap-${i}.xml`;

       sitemapStream
        .pipe(fs.createWriteStream(resolve(path + ""))); // write it to sitemap-NUMBER.xml

        return [new URL(path, domain).toString(), sitemapStream];
     }
    });
```


```
    sms.pipe(fs.createWriteStream(resolve("./sitemap-index.xml")));

     let arrayOfSitemapItems = await getUrls();

    
     arrayOfSitemapItems.forEach(item => sms.write(item));
     sms.end();

     let xml = await streamToPromise(SMS)

     console.log("xml",xml);

```

**Comment by derduher** [comment]
sms.end needs to be called after stream to promise. I suggest converting the await to a traditional promise. Otherwise you are closing the stream without having written anything out yet. It doesn't start pulling on the stream until streamToPromise is invoked as it has nowhere to write.

```js
arrayOfSitemapItems.forEach(item => sms.write(item));
     

streamToPromise(sms).then(xml => console.log(xml))
sms.end();
```

**Comment by derduher** [comment]
I'm going to try to improve the error message for this case and the documentation around streams in general.

**Comment by waleedarshad-vf** [comment]
Seems like in your testcase. you are closing before
I will follow your steps and let you know

  const smis = new SitemapItemStream();
    smis.write(testData);
    smis.end();
    expect((await streamToPromise(smis)).toString()).toBe(...

**Comment by derduher** [comment]
Curious. I'm not sure why that worked.
