### ISSUE TITLE
[ BUG ] <Why it's wraps the image title and caption with '<![CDATA['

### ISSUE THREAD

**Issue by hrhitesh** [ekalinin/sitemap.js#319]
**Describe the bug**
I have an issue that when I want to add a title and caption to the image, it always wraps my image title and caption text with '<![CDATA['

**Expected behavior**
I don't want that '<![CDATA['.

**Context:**
 - Library Version [e.g. 1.13.0]

**Additional context**
Would be great if I can disable it by sending any flags or something else. Also right now my project is stable and I don't want to update to the latest version which is too complex (as syntax and functions are changed).

Can anyone here able to resolve these issues OR with a great alternate for this?
Thanks

**Comment by derduher** [comment]
The latest version does not wrap the text in CDATA. What version are you on?

**Comment by derduher** [comment]
Also can you give me an idea of your usecase and what you find difficult about the newer interface? I will use this to improve / simplify things.

**Comment by hrhitesh** [comment]
> The latest version does not wrap the text in CDATA. What version are you on?

@derduher I'm using 1.13.0 version.

**Comment by derduher** [comment]
It looks like that version hard-codes the CDATA https://github.com/ekalinin/sitemap.js/blob/1.13.0/lib/sitemap.js#L160. If upgrading is too scary, you can try forking removing the CDATA from the code and install from a github tag in npm eg hrhitesh/sitemap.js#custom-tag

**Comment by hrhitesh** [comment]
@derduher Yeah, right. Thanks for that alternative.
BTW I have found that Version 5.0.0 is similar to 1.13.0 version which does have the same function name and functionality.

Thanks again

**Comment by derduher** [comment]
From there you are only a couple steps from the latest. Feel free to ask questions or raise any concerns if/when you wish to update to the latest.
Closing since it seems you have resolved your issue. Feel free to reopen.
