### ISSUE TITLE
[ BUG ] simpleSiteMapAndIndex error

### ISSUE THREAD

**Issue by moonmeister** [ekalinin/sitemap.js#322]
**Describe the bug**
```
       throw ex;
        ^

Error: ENOENT: no such file or directory, open 'C:\Users\Alex\code\moonmeister\moonmeister.net\public\sitemap.xml\sitemap-0.xml.gz'
Emitted 'error' event on WriteStream instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at WriteStream.onerror (_stream_readable.js:753:7)
    at WriteStream.emit (events.js:315:20)
    at internal/fs/streams.js:376:12
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Alex\\code\\moonmeister\\moonmeister.net\\public\\sitemap.xml\\sitemap-0.xml.gz'
}
error Command failed with exit code 7.
```
All day everyday. Wondering if it's a windows bug

**Expected behavior**
I'd expect it to no fail and write the files to disk.

**Context:**
 - Library 6.0.2

**Additional context**
Node LTS 12

**Comment by derduher** [comment]
based off the error it looks like you are passing a directory that does not exist. based off the name I think you were trying to pass a file to the directory argument.

**Comment by moonmeister** [comment]
This is outputting (based on the defaults) to a build directory, it could not exist at any given build. I would expect sitemap be creating the destination directory if it doesn't exist, since it's handling all other file related things.

**Comment by derduher** [comment]
That makes sense. This particular wrapper is only a couple days old so there's bound to be usability bugs. I'll keep this open to change that behavior but once you changed the path did things work ok for you?

**Comment by moonmeister** [comment]
Yeah, changing the path to an existing directory resolved the issue. Thanks for your work on this project, this simple function in particular is nice to have.  I will add, it would be nice to have an option to not gzip the sitemaps.
