### ISSUE TITLE
[ BUG ] <Upgrading the package version to 5.0.0 having issue of "allocation failure GC in old space requested">

### ISSUE THREAD

**Issue by hrhitesh** [ekalinin/sitemap.js#323]
**Describe the bug**
I was using the old package version 1.13.0. After upgrading the version to 5.0.0 to resolve this [issue](https://github.com/ekalinin/sitemap.js/issues/319). But now I'm having an issue with memory with the same code that is perfectly running with version 1.13.0.
This is my error:
````
<--- Last few GCs --->

[16939:0x39aedd0] 339069 ms: Mark-sweep 1409.2 (1724.0) -> 1409.2 (1724.0) MB, 1322.4 / 0.0 ms allocation failure GC in old space requested
[16939:0x39aedd0] 340302 ms: Mark-sweep 1409.2 (1724.0) -> 1409.0 (1670.0) MB, 1232.4 / 0.0 ms last resort
[16939:0x39aedd0] 341533 ms: Mark-sweep 1409.0 (1670.0) -> 1409.0 (1657.0) MB, 1230.6 / 0.0 ms last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x10516c028799 <JSObject>
1: stringSlice(aka stringSlice) [buffer.js:~549] [pc=0xff6e55ce10](this=0xa77f7002311 <undefined>,buf=0x25d7de926de1 <Uint8Array map = 0x317a81943021>,encoding=0x10516c06f5e9 <String[3]: hex>,start=0,end=277375)
````

**Expected behavior**
I want to be run and execute with no failure and no memory issue.

**Context:**
 - Library Version [5.0.0]

**Additional context**
Please help me out to solve this issue.

**Comment by derduher** [comment]
I suspect this is an underlying dependency (XMLbuilder) that was removed in version 6. Part of the reason I switched the library to streams was it took up so much memory. v5 has streams, you can try switching to those or updating to v6. You can also try [this](https://stackoverflow.com/questions/46688918/nodejs-memory-allocation-failure) - though that really should only be done if the other two aren't feasible as you really shouldn't /need/ a lot of memory.
Sorry there isn't a quick and easy solution.

**Comment by derduher** [comment]
I also recently introduced a "simplifiedSitemapAndXML" function that should be easy to use on v6.2.0 See the the readme for details. (assuming you just want to write the files to disk)

**Comment by hrhitesh** [comment]
Thanks for the quick response @derduher. I will check this and get back to you if it's resolved.
