### ISSUE TITLE
[ BUG ] Type definition of dataSource param of simpleSitemapAndIndex is wrong

### ISSUE THREAD

**Issue by pinkiebala** [ekalinin/sitemap.js#331]
**Describe the bug**
Currently, the type of dataSource param of simpleSitemapAndIndex has an option is `SitemapItemLoose`.
https://github.com/ekalinin/sitemap.js/blob/769f23d0e909f51b62a51bf32936c153143c1edd/lib/sitemap-simple.ts#L28

But the example in Readme can't work

```
sourceData: [{ url: '/page-1/', changefreq: 'daily'}]
```

**Expected behavior**
I believe the type should be `SitemapItemLoose[]`

**Context:**
 - Library Version 6.3.0

**Additional context**

**Comment by derduher** [comment]
@pinkiebala Thanks for filing this. A patch has now been released. I wish there was such a thing as "type coverage" so I could add that as a thing to check for.
