### ISSUE TITLE
How to update to newest version?

### ISSUE THREAD

**Issue by MarcGodard** [ekalinin/sitemap.js#332]
I used to use the sitemap as middleware like this:

```javascript
const sm = require('sitemap')

  app.use('/sitemap.xml', serviceOptions, (req, res, next) => {
    if (req.method === 'GET') {
      const urls = res.data
      const domain = app.get('protocol') + '://' + app.get('domain')
      const siteMap = sm.buildSitemapIndex({
        hostname: domain,
        cacheTime: 600000,
        sitemapName: 'sitemap',
        urls,
        xslUrl: '/xsl/xml-index-sitemap.xsl'
      })

      res.header('Content-Type', 'application/xml')
      res.send(siteMap)
    } else {
      next()
    }
  })
```

Where urls is the list, and this worked very well. Now I am updating the packages and can't figure out how to use the new methods in the same way. I don't want to build files to serve, as this is on a resetting container and the files will simply not exist when the container reboots, so I just want to serve the xml.

Which method do I use... maybe I am missing something, but not sure how to upgrade.

**Comment by derduher** [comment]
@MarcGodard its a slight tweak on this example https://github.com/ekalinin/sitemap.js#serve-a-sitemap-from-a-server-and-periodically-update-it, You use [Readable.from](https://nodejs.org/api/stream.html#stream_stream_readable_from_iterable_options) to turn your array into a stream, then pipe the options into the SitemapStream or SitemapIndexStream. Wrap the pipeline in streamToPromise and you'll have your single value. The example also demonstrates caching in the first couple lines `if (sitemap)` that's been moved out of the library and is up to you to implement.
If you need more details, let me know.

**Comment by MarcGodard** [comment]
Awesome, thanks. Got it all working.
