### ISSUE TITLE
[question] simpleSitemapAndIndex gzip option

### ISSUE THREAD

**Issue by soso01** [ekalinin/sitemap.js#334]
When the simpleSitemapAndIndex gzip option is used, 
sitemap-0.xml is added from the sitemapIndex.gz file, 
but the actually created file is sitemap-0.xml.gz, so it cannot be referenced.

Is there anything else I need to set up

**Comment by derduher** [comment]
sorry for not looking into this until now. It's been a crazy year.

**Comment by Vrq** [comment]
Is this a bug or what is the answer? @derduher

**Comment by derduher** [comment]
@Vrq it was fixed in 6.3.3

**Comment by Vrq** [comment]
Thanks! Haven't noticed it :)
