### ISSUE TITLE
[ BUG ] Concatenation of absolute paths in alternate links

### ISSUE THREAD

**Issue by Lunatic174** [ekalinin/sitemap.js#335]
I'm trying to add links to alternate language page, which has different domain name.
According to google sitemap rules, it's legal.

Me code:
```typescript
const smStream = new SitemapStream({hostname: 'https://example.ru/'})

smStream.write({
    url: '/docs',
    links: [
        {lang: 'ru', url: 'https://example.ru/docs'},
        {lang: 'en', url: 'https://example.com/docs'}
    ]
});
```

I'm expecting to get this:
```xml
<url>
    <loc>https://example.ru/docs</loc>
    <xhtml:link rel="alternate" hreflang="ru" href="https://example.ru/docs"/>
    <xhtml:link rel="alternate" hreflang="en" href="https://example.com/docs"/>
</url>
```

But instead I've got this:
```xml
<url>
    <loc>https://example.ru/docs</loc>
    <xhtml:link rel="alternate" hreflang="ru" href="https://example.ru/example.ru/docs"/>
    <xhtml:link rel="alternate" hreflang="en" href="https://example.ru/example.com/docs"/>
</url>
```

I temporarily fixed this by removing the `hostname` option and specifying absolute paths everywhere. 
But i'm suppose that the correct behaviour is to check for absolute url.

**Context:**
 - Library Version [6.3.2]

**Comment by derduher** [comment]
@Lunatic174 After attempting to reproduce your example in tests and standalone scripts on node 10, 12, 14 I always got the correct result. The example you gave is pretty straightforward so I'm not sure what is going on. What version of node are you on? Under the hood the hostname is added via `new URL(url, hostname)` perhaps something is different with URL on your instance?

**Comment by Zae** [comment]
I'm having the same problem but with a subdomain I think.

When I use the hostname `https://example.com` and add `https://sub.example.com` in my sitemap I get the following url in the sitemap:

`https://example.com/sub.example.com`

I'm using node v10.23.0 (and nuxt-sitemap-module) but that uses this package to generate the actual sitemap :)

**Comment by derduher** [comment]
closing for lack of reproducible example

**Comment by yoavaviram** [comment]
I'm having the same issue. 

Code:
`    const smStream = new SitemapStream({ hostname: "https://yourdigitalrights.org/" })

    smStream.write({
      url: "/about",
      changefreq: "weekly",
      priority: 1,
      links: [
        { lang: 'es', url: 'https://es.yourdigitalrights.org/about' },
        { lang: 'it', url: 'https://it.yourdigitalrights.org/about' }
      ],
    });
`

Expecting:
`
<url>
  <loc>https://yourdigitalrights.org/about</loc>
  <changefreq>weekly</changefreq>
  <priority>1.0</priority>
  <xhtml:link rel="alternate" hreflang="es" href="https://yourdigitalrights.org/about"/>
  <xhtml:link rel="alternate" hreflang="it" href="https://yourdigitalrights.org/about"/>
</url>
`

Got:
`
<url>
  <loc>https://yourdigitalrights.org/about</loc>
  <changefreq>weekly</changefreq>
  <priority>1.0</priority>
  <xhtml:link rel="alternate" hreflang="es" href="https://yourdigitalrights.org/es.yourdigitalrights.org/about"/>
  <xhtml:link rel="alternate" hreflang="it" href="https://yourdigitalrights.org/it.yourdigitalrights.org/about"/>
</url>
`

Context:

    Library version [6.4.0]
    Node version:  [15.11.0]

Let me know if there's anything else you need to reproduce.

**Comment by derduher** [comment]
Thanks @yoavaviram I'll give it a shot tonight

**Comment by yoavaviram** [comment]
Thanks!

**Comment by derduher** [comment]
Hi @yoavaviram This is what I get on node 14.5 
```
<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1"><url><loc>https://yourdigitalrights.org/about</loc><changefreq>weekly</changefreq><priority>1.0</priority><xhtml:link rel="alternate" hreflang="es" href="https://es.yourdigitalrights.org/about"/><xhtml:link rel="alternate" hreflang="it" href="https://it.yourdigitalrights.org/about"/></url></urlset>
```
```
const smStream = new SitemapStream({
  hostname: 'https://yourdigitalrights.org/',
});

smStream.write({
  url: '/about',
  changefreq: 'weekly',
  priority: 1,
  links: [
    { lang: 'es', url: 'https://es.yourdigitalrights.org/about' },
    { lang: 'it', url: 'https://it.yourdigitalrights.org/about' },
  ],
});
smStream.end();

streamToPromise(smStream)
  .then((sm) => console.log(sm.toString()))
  .catch(console.error);
```

**Comment by derduher** [comment]
and in node 16.0.0

**Comment by yoavaviram** [comment]
hi @derduher , thanks for looking into this. Not sure why I was getting this issue but I moved on to use a different solution (alternate links on page rather then in the sitemaps), so it might have been some env problem on my side. If this works for others you can close this issue.
