### ISSUE TITLE
[Feature] Support languages - hreflang

### ISSUE THREAD

**Issue by codler** [ekalinin/sitemap.js#340]
https://developers.google.com/search/docs/advanced/crawling/localized-versions

**Comment by derduher** [comment]
[hreflang is supported](https://github.com/ekalinin/sitemap.js/blob/master/api.md#sitemap-item-options), there is a bug where for now all links need to be absolute #335. Might be able to fix that over break. Also checkout #335 for an example on its use.

**Comment by codler** [comment]
Thank you!
