### ISSUE TITLE
[question] How to remove trailing slash for base root sitemap in sitemapStream?

### ISSUE THREAD

**Issue by qipoy** [ekalinin/sitemap.js#345]
if I generated a sitemap URL everything is good, but my base URL always got a trailing slash.
can I remove that?

**Comment by derduher** [comment]
Ultimately the baseurl you provide is fed into [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) along with your individual url path.
While I can see how you can feed in a base url such as `http://example.com/subpath` and `""` and still get out `"http://example.com/subpath"`
There is no way to feed in `http://example.com` and `""` and not have it append the slash. <-- This is true only for the domain without any path.
You can play with this by opening your browser's console and playing with the results `new URL('', 'http://example.com/foo').toString()` 

If that still does not help you please provide a more concrete example
