### ISSUE TITLE
[ BUG ] Unhandled tag for "content_loc" in video sitemap

### ISSUE THREAD

**Issue by saurabhd** [ekalinin/sitemap.js#347]
**Describe the bug**
I tried to use sitemap@6.3.6 version and used a sample XML file which has video tag with appropriate namespaces attached in the XML. The script correctly parses the XML and produces the video entities information in JSON format except `content_loc`. As per my findings, the tag is not handled [here](https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap-parser.ts#L37) and [here](https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap-parser.ts#L163). When I put the same in the compiled JS version, it starts getting the `content_loc` in JSON format correctly.

**Expected behavior**
It should detect `content_loc` along with other video tag fields.

**Context:**
Sitemap 6.3.6 version used.

**Additional context**
Let me know if anymore information needed in order to reproduce this, thanks.

**Comment by saurabhd** [comment]
@ekalinin @derduher - for your kind consideration, please. Thanks

**Comment by derduher** [comment]
Looks like I missed implementing this feature. Thanks for finding this.
fixed in #350 6.4.0
