### ISSUE TITLE
[question] Creating/overwriting sitemap file

### ISSUE THREAD

**Issue by puz1ngg1** [ekalinin/sitemap.js#351]
I need to be able to create/overwrite sitemap file. On my backend there is a GET /sitemap.xml endpoint which gives back a sitemap file with already dynamically created urls and I just need to request and read/write that file with response, so that every time someone or crawlers try to read sitemap file, it sends a request for endpoint and shows the response with already existing urls/lastmods etc. Could you provide some piece of code or links how to resolve my issue?

**Comment by derduher** [comment]
No, but maybe someone else will come along and generously provide you with some sample code for your use-case.

**Comment by huntharo** [comment]
@derduher - I think maybe this should be closed?  Issue seems unclear and beyond the scope of the library itself?
