### ISSUE TITLE
[ BUG ] The dest file created by SitemapIndexStream not works on Google Search Console

### ISSUE THREAD

**Issue by JerroldLee** [ekalinin/sitemap.js#352]
**Describe the bug**
The output content not the same as document by https://github.com/ekalinin/sitemap.js/blob/master/api.md#sitemapindexstream,
I got like 
```
<sitemap>
      <loc url="https://example.com/"/>
 </sitemap>
```

**Expected behavior**
Expect output to be like this
```
<sitemap>
      <loc>https://example.com/</loc>
</sitemap>
```

**Context:**
 - Library Version 6.4.0

**Comment by derduher** [comment]
Cannot reproduce
