### ISSUE TITLE
[question] How can we encode local languages properly?

### ISSUE THREAD

**Issue by Thayakaran** [ekalinin/sitemap.js#353]
when I pass a Tamil word in URL its shows as encoded characters, but the URL works on browsers. will it be an issue for crawlers to read?

Thank you.

```
	<url>
		<loc>
			https://example.com/page-%E0%AE%A4%E0%AF%8A%E0%AE%9F%E0%AE%B0%E0%AF%8D%E0%AE%AA%E0%AF%81-1
		</loc>
		<lastmod>
			2021-03-25T12:16:56.592Z
		</lastmod>
		<changefreq>
			daily
		</changefreq>
		<priority>
			0.6
		</priority>
	</url>
```

**Comment by derduher** [comment]
Should be fine. URLs don't support non-ascii characters. when you enter non-ascii into your browser it will automatically translate that into something like what you see above. So the above is the output of that translation done on your behalf for crawlers sake.
