### ISSUE TITLE
Why don't SitemapIndexStream have lastmodDateOnly option?

### ISSUE THREAD

**Issue by maximka777** [ekalinin/sitemap.js#356]
I see that `SitemapStream` has `lastmodDateOnly` option:
```js
new SitemapStream({
  // ...
  lastmodDateOnly: true
});
```
but `SitemapIndexStream` doesn't.

I think it would be nice to have the option in both. Correct me please if I'm wrong.

UPD: same about `hostname` option.

**Comment by derduher** [comment]
lastmodDateOnly is a pretty niche feature. It seems to only be required in specialized cases. You are welcome to open a PR to add support.
