### ISSUE TITLE
[ BUG ] Incorrect sitemap path in sitemap index

### ISSUE THREAD

**Issue by moonmeister** [ekalinin/sitemap.js#359]
**Describe the bug**
when using `simpleSitemapAndIndex` I noticed in the `sitemap-index.xml` the paths to the sub index paths don't cotain the subfolder (`destinationDir`) in the path. 

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://example.net/sitemap-0.xml</loc>
  </sitemap>
</sitemapindex>

```

**Expected behavior**
The location should contain the destination directory. 

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://example.net/sitemap/sitemap-0.xml</loc>
  </sitemap>
</sitemapindex>

```

**Context:**
 - version: 6.3.0

**Comment by moonmeister** [comment]
Affects https://github.com/gatsbyjs/gatsby/issues/31167

**Comment by derduher** [comment]
@moonmeister I'll be releasing a version shortly that has support for a publicBaseUrl so you can specify a non-root base url for sitemaps.

**Comment by moonmeister** [comment]
This doesn't appear to be fixed.

**Comment by moonmeister** [comment]
Well...now I'm just confused. So you added `publicBasePath` but `destinatioDir` already existed to do this...or is destination dir suppose to be something different?

**Comment by derduher** [comment]
Destination dir is the location on disk. Publicbasepath is the base URL for
site map files. The location you write the files to may coincidentally
share the same path.

**Comment by moonmeister** [comment]
Okay, that makes sense now, maybe i missed some docs clarifying that but didn't realize that was the case.
