### ISSUE TITLE
Exit Code on Failed Validation

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [ekalinin/sitemap.js#378]
**Is your feature request related to a problem? Please describe.**
When usng the validate feature, if the xml is invalid, the error is caught and the error message is printed with console.log. This prevents my script from failing when the xml file I am generating is invalid.

**Describe the solution you'd like**
I would like for sitemap to return an exit code of 1 when the xml is invalid, instead of return an exit code of 0. You can add `process.exitCode = 1` to exit with 1 whenever sitemap does exit, or you can make it exit right then and there with 1 by adding `process.exit(1)`. This would placed right after the console.log that prints the caught error message.

**Comment by derduher** [comment]
The fix for this is merged and will be released in the next couple of days.
