### ISSUE TITLE
[ BUG ] parseSitemapIndex not included in 7.1.0 release

### ISSUE THREAD

**Issue by tomcek112** [ekalinin/sitemap.js#384]
**Describe the bug**
The `parseSitemapIndex` method, as introduced in #370, is not included in the latest `7.1.0` release.

**Expected behaviour**
The method should be included & exported by the final bundle.

**Context:**
 - Library Version `7.1.0`

**Additional context**
Not sure if I'm understanding the release cycle of this library incorrectly but I can see the PR merged & the file on `master`. However, I neither see a reference to it in the `CHANGELOG.md`, nor can I find it in the bundle as published to the NPM repo. Is this feature still WIP or just an oversight?

Thanks for having a look at this and also a great thank you for providing & maintaining this library in the first place!

**Comment by huntharo** [comment]
AHHH!!!!   Good catch, thanks!
