### ISSUE TITLE
Doesn't normalize urls

### ISSUE THREAD

**Issue by ismay** [ekalinin/sitemap.js#39]
So: 

`hostname: 'http://website.com'` with `url: 'page.html'` => `http://website.compage.html`
`hostname: 'http://website.com/'` with `url: '/page.html'` => `http://website.com//page.html`

I'd expect this module to remove and add slashes where necessary.

**Comment by ismay** [comment]
If you use a package like https://www.npmjs.com/package/url-join to join the different parts [here](https://github.com/ekalinin/sitemap.js/blob/master/lib/sitemap.js#L317) this problem would be solved.

**Comment by ekalinin** [comment]
Hi @ismay 

Thanks for report.

**Comment by ismay** [comment]
:+1:
