### ISSUE TITLE
[Feature] Keep a record of the parent node

### ISSUE THREAD

**Issue by ideiasfrescas** [ekalinin/sitemap.js#398]
**Is your feature request related to a problem? Please describe.**
We would like to create a visual hierarchical graph of the sitemap, but building it from the the sitemap.xml is complicated and requires another process, after the sitemap is complete.

**Describe the solution you'd like**
On [SitemapIndexOptions](https://github.com/ekalinin/sitemap.js/blob/master/api.md#sitemap-item-options) somekind of property to keep track of the immediate parent ( or parents if the url results on the same page ).

**Additional context**
Check this pen [2nd example](https://codepen.io/ross-angus/pen/jwxMjL)

**Comment by derduher** [comment]
Out of scope
