### ISSUE TITLE
Async-style API ignores error thrown by `.toString()`

### ISSUE THREAD

**Issue by kemskems** [ekalinin/sitemap.js#40]
In `lib/sitemap.xml` you have this:
```javascript
Sitemap.prototype.toXML = function (callback) {
  if (typeof callback === 'undefined') {
    return this.toString();
  }
  var self = this;
  process.nextTick( function () {
    if (callback.length === 1) {
      callback( self.toString() );
    } else {
      callback( null, self.toString() );
    }
  });
}
```
However, `Sitemap.prototype.toString()` may throw error, since it will call `new SitemapItem()` and that may throw error too (when there is no URL, no protocol, etc). The async-style API never pass the error to the callback so the error becomes an uncaught exception, which will kill Node process. How about changing `.toXML()` to:
```javascript
Sitemap.prototype.toXML = function (callback) {
  if (typeof callback === 'undefined') {
    return this.toString();
  }
  var self = this;
  process.nextTick( function () {
    try {
      return callback(null, self.toString());
    } catch (err) {
      return callback(err);
    }
  });
}
```
I know this will break backward compatibility but I think this is the proper way to do it. If agreed, I can work on this.

**Comment by ekalinin** [comment]
Hi @kemskems 

Yeah, looks good for me. Please, create a PR for it.

**Comment by kemskems** [comment]
Hi @ekalinin. I have made a PR for this (#41). Please take a look.

**Comment by ekalinin** [comment]
Thanks!
