### ISSUE TITLE
[Feature] Specify lastmod attribute per url link

### ISSUE THREAD

**Issue by Thomas-1985** [ekalinin/sitemap.js#409]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is there a way to specify the `lastmod` attribute per url link. So something like this (which can be updated if content changes)
```
  links: [
    { lang: 'en', url: 'http://test.com/page-1/', lastmod: '2023-01-01' },
    { lang: 'de', url: 'http://test.com/page-1/de/', lastmod: '2023-02-01' }
  ],
```

This would be extremely helpful

**Comment by huntharo** [comment]
Unfortunately, while this could be done, it would not be valid and would not be followed by any crawlers.

The `link` is actually an `xhtml:link`: 
- https://developers.google.com/search/docs/specialty/international/localized-versions?visit_id=638517720220365930-3724444723&rd=1#sitemap
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

You can see that it has `rel` and `alternate` fields but it does not have a`lastmod` field.
