### ISSUE TITLE
[ BUG ] Sitemap not generated when url count is less than 5. 

### ISSUE THREAD

**Issue by vikaskrsharma** [ekalinin/sitemap.js#419]
When generating a sitemap xml using SitemapStream and if number of items write is less than 5 ie number of items passed for url generation is less than 5, generated xml does not show any data. For 5 or more item/urls, it is working fine.

**Comment by huntharo** [comment]
Do you have example code for this?

**Comment by huntharo** [comment]
@derduher - I think we can close this as a duplicate of #362

**Comment by vikaskrsharma** [comment]
@huntharo As i am not working on this project anymore, can't paste the code. but the case was, if i am passing less than 5 url to the SitemapStream, i am getting nothing in sitemap url. but i pass 6 or more url, i was getting sitemap with all urls.  As per your test, this case should fail. but when was using it on my env, this was the actual behaviour.
