### ISSUE TITLE
Sitemap Styling

### ISSUE THREAD

**Issue by AnimaMundi** [ekalinin/sitemap.js#43]
An option to add a style sheet would be greatly appreciated!

**Comment by ekalinin** [comment]
It's already there.
Added in #38.
See the option `xslUrl` in the constructior.

**Comment by AnimaMundi** [comment]
Apologies on not reading the source code...
I guess the point of using a module like this is that I don't have to spend time doing stuff like that,
but thanks for adding the example to the documentation. This module has come in dead handy!

**Comment by ekalinin** [comment]
> Apologies on not reading the source code...

No problem :)

> but thanks for adding the example to the documentation. This module has come in dead handy!

You're welcome!
