### ISSUE TITLE
No appropriate support for urls with hashbang #!

### ISSUE THREAD

**Issue by papaiatis** [ekalinin/sitemap.js#45]
I have an AngularJs powered website which uses hashbang (#!) in the URLs.
I tried setting my hostname and map url to every possible way but couldn't make the hashbang url work.

For example my url is: "www.example.com/#!/home". No matter what I configure I always get "www.example.com#!/home". Note the missing slash after dot com.

It might be a bug in the "url-join" component. Please investigate.

**Comment by R3VoLuT1OneR** [comment]
I got same bug and yes it is "url-join" bug/feature "www.example.com/#!/home" it is not so correct url.

But to fix it on your side, I can suggest you not pass "hostname" in params and provide full urls, with domain name.

Example: 
```javascript
var sitemap = sm.createSitemap ({
      // hostname: 'http://example.com',
      cacheTime: 600000,        // 600 sec - cache purge period
      urls: [
        { url: 'www.example.com/#!/page-1/',  changefreq: 'daily', priority: 0.3 },
        { url: 'www.example.com/#!/page-2/',  changefreq: 'monthly',  priority: 0.7 },
        { url: 'www.example.com/#!/page-3/'},    // changefreq: 'weekly',  priority: 0.5
        { url: 'www.example.com/#!/page-4/',   img: "http://urlTest.com" }
      ]
});
```

**Comment by ekalinin** [comment]
Yeah, thanks @R3VoLuT1OneR

**Comment by rauberdaniel** [comment]
I just submitted a pull request to url-join which fixes this issue. It already got merged and published with version 1.1.0. So you only should need to update the version and it should work.

**Comment by ekalinin** [comment]
Thanks @rauberdaniel !

**Comment by robixxu** [comment]
this is still a issue i'm using the last version of url-join which has that fix merged but the separator is still stripped.
