### ISSUE TITLE
Add support for image:caption

### ISSUE THREAD

**Issue by papaiatis** [ekalinin/sitemap.js#46]
Please add support for `<image:caption>` as it is seen here: https://support.google.com/webmasters/answer/183668

Thank you!!

**Comment by nguyenngocphuongnb** [comment]
This pull also supported for image:caption
https://github.com/ekalinin/sitemap.js/pull/63

**Comment by rauberdaniel** [comment]
I created a new pull request which adds support for image:caption (as #63 by @nguyenngocphuongnb has some issues) including tests and example
