### ISSUE TITLE
Priority 0 gets removed from the sitemap

### ISSUE THREAD

**Issue by redhat-raptor** [ekalinin/sitemap.js#50]
Priority 0 gets removed from sitemap. Should it not show: <code>&lt;priority&gt;0.0&lt;/priority&gt;</code> instead?

Also setting priority to 1 shows as 1 in sitemap XML. Would that be wise to always print 1 decimal point in the XML e.g. 1 becomes <code>&lt;priority&gt;1.0&lt;/priority&gt;</code> always!

**Comment by ekalinin** [comment]
Fixed by #51
