### ISSUE TITLE
Error while deploying to GCLOUD

### ISSUE THREAD

**Issue by dorshay6** [ekalinin/sitemap.js#53]
I get the Error

ERROR: (gcloud.preview.app.deploy) Error Response: [400] Invalid character in filename: node_modules/sitemap/env/lib/python2.7/site-packages/setuptools/script (dev).tmpl

**Comment by ekalinin** [comment]
Hi @dorshay6 

Hm, seems like this file (`env/lib/python2.7/site-packages/setuptools/script (dev).tmpl`) is not from this project :)
