### ISSUE TITLE
What is the point of cache?

### ISSUE THREAD

**Issue by babbelnedd** [ekalinin/sitemap.js#55]
Sure, when adding pages while the app is running. Makes totally sense.

But how do I replace urls, since they are passed as array at creation time.

**Comment by ekalinin** [comment]
Hi @babbelnedd 

> What is the point of cache?

To store the result xml of the sitemap. 
And do not repeat all that logic for formatting the sesult xml for each request.

> But how do I replace urls, since they are passed as array at creation time

Like this (full example see in the `README`):

```javascript
sitemap.add({url: '/page-2/', changefreq: 'monthly', priority: 0.7});
sitemap.del({url: '/page-2/'});
```
