### ISSUE TITLE
Enable Deep Links in sitemap

### ISSUE THREAD

**Issue by kamoljan** [ekalinin/sitemap.js#56]
Hi @ekalinin 

do you provide an additional parameter for [deep linking](http://developer.android.com/training/app-indexing/enabling-app-indexing.html#sitemap)?

example:

     <xhtml:link rel="alternate" href="android-app://com.example.android/example/gizmos" />

**Comment by ekalinin** [comment]
Hi @kamoljan 

Nope :(
There's only support for the [alternate language pages](https://github.com/ekalinin/sitemap.js/blob/43e4a5a2493f7498d7082fa0fb6eb32c08ea1f7e/README.md#example-of-indicating-alternate-language-pages).

**Comment by kamoljan** [comment]
Hi @ekalinin that's good enough! :+1:  :bow:

**Comment by kamoljan** [comment]
Sorry @ekalinin `alternate language pages` is not enough.
But very close.
Let's make it? :) :+1:

**Comment by ekalinin** [comment]
Let's try :)

**Comment by dushmantha** [comment]
+1

**Comment by markelarizaga** [comment]
This addition would be great, so here is my +1 too.

**Comment by markelarizaga** [comment]
Pull request created, hope it's good enough and gets merged.

**Comment by ekalinin** [comment]
Should be fixed by #73
