### ISSUE TITLE
How to test the package?

### ISSUE THREAD

**Issue by felixsanz** [ekalinin/sitemap.js#58]
When i install it, i see no "tests" folder, you forgot to add it into npm? or it's my fault that i'm missing some extra command?

Thanks!

**Comment by ekalinin** [comment]
Hey @felixsanz 

Here's my way:

```
➥ git clone https://github.com/ekalinin/sitemap.js.git
➥ cd sitemap.js
➥ make env 
➥ . env/bin/activate
(env) ➥ make test
./node_modules/expresso/bin/expresso ./tests/sitemap.test.js

   100% 33 tests
```

**Comment by ekalinin** [comment]
Added this info into README:
  * https://github.com/ekalinin/sitemap.js#testing
