### ISSUE TITLE
Can't test the package

### ISSUE THREAD

**Issue by felixsanz** [ekalinin/sitemap.js#59]
According to readme...

```
make env 
make: *** No rule to make target 'env'.  Stop.
```

Please don't close the issue this time. Thanks!

**Comment by ekalinin** [comment]
1. Would you be able to show the full list of commands you did? (with git clone)
2. What OS do you use?
3. You can re-open old issue if you think that problem wasn't fixed.

**Comment by ekalinin** [comment]
4. If you have globaly installed nodejs then try this:
```bash
➥ git clone https://github.com/ekalinin/sitemap.js.git
➥ cd sitemap.js
➥ npm install
➥ make test
```

**Comment by felixsanz** [comment]
oh, i did not do git clone. i did npm install!
