### ISSUE TITLE
Ability to use HH:MM:SS in lastmod

### ISSUE THREAD

**Issue by felixsanz** [ekalinin/sitemap.js#61]
The code says:

> // The date of last modification (YYYY-MM-DD)

It is possible to specify the hour/minute/second somehow or needs PR?

**Comment by ekalinin** [comment]
Hey @felixsanz 

Yes, it's possible :)
Please, look on this comment:
  * https://github.com/ekalinin/sitemap.js/issues/16#issuecomment-57186652
