### ISSUE TITLE
Use jstoxml instead of doing string concatenation everywhere

### ISSUE THREAD

**Issue by rauberdaniel** [ekalinin/sitemap.js#65]
What do you think about using a dependency (e.g. https://github.com/davidcalhoun/jstoxml) to create a valid xml output instead of doing string concatenations? In my opinion this would definitely make the code easier to understand and maintain.

**Comment by ekalinin** [comment]
Hey @rauberdaniel 

Thanks for the propose. 
But to be honest i don't want to add one more dependency.
But will think about it.

**Comment by derduher** [comment]
We have since updated to use xml builder lib. So we are no longer manually concatenating strings.
