### ISSUE TITLE
Split sitemaps up for large volume.

### ISSUE THREAD

**Issue by woodyrew** [ekalinin/sitemap.js#66]
Sitemaps files shouldn't exceed 10MB or 50,000 URLs per file. This means you need a sitemap index file. I couldn't see this in the api, can it be done already?

For more infomation, see: http://www.sitemaps.org/faq.html#faq_sitemap_size

**Comment by woodyrew** [comment]
Thanks for the clarification :+1:

**Comment by ekalinin** [comment]
You're welcome :)
