### ISSUE TITLE
expires tag

### ISSUE THREAD

**Issue by fantapop** [ekalinin/sitemap.js#68]
Hi,

I'm interested in adding the expires tag to my sitemap for use with Google Custom Search as described here: https://developers.google.com/custom-search/docs/indexing#on-demand-removal

It doesn't look like there's currently a way to do this with sitemap.js.  Is this something you'd feel okay with being in the project? I realize its not currently a standard.

**Comment by ekalinin** [comment]
Hey @fantapop 

> It doesn't look like there's currently a way to do this with sitemap.js.

Yes, this tag isn't supported at the moment.

> Is this something you'd feel okay with being in the project?

I have nothing against it :) Feel free to create a PR.

**Comment by Mickael-van-der-Beek** [comment]
@ekalinin I created the PR for this here: https://github.com/ekalinin/sitemap.js/pull/100

**Comment by ekalinin** [comment]
Thanks! Merged.
