### ISSUE TITLE
Hash in url root, separator is stripped

### ISSUE THREAD

**Issue by tomvlk** [ekalinin/sitemap.js#70]
When using url's like this:

```
url: '/#/home'
```

it get's stripped as:

```
https://hostname.com#/home
```

**Comment by ekalinin** [comment]
Hey @tomvlk 

I'm using this tool for url joining: https://github.com/jfromaniello/url-join/
Btw, did you try:
```
url: '/#!/home'
```
?

See more details in #45

**Comment by tomvlk** [comment]
Well, this is what I'm trying right now:

```javascript
sitemap.add({
  url: '/#!/list',
  changefreq: 'daily',
  priority: 0.8
});
```

and the result of the XML is:
```xml
<url>
      <loc>https://hostname.com/#!/list</loc>
      <changefreq>daily</changefreq>
      <priority>0.8</priority>
</url>
```

And with the current site /#1/ is not working right, where /#/ is.

**Comment by KerrGrah** [comment]
I was able to get around this issue by including the entire url starting from https...  so that url-join is not invoked at 
`if (!reProto.test(link.url)) {
            link.url = urljoin(self.hostname, link.url);
        }`
seems like you left a good way out!

**Comment by ECnetHub** [comment]
The same issue on Angular AP.

**Comment by crisp2u** [comment]
The relevant issue on url-join is https://github.com/jfromaniello/url-join/issues/10

**Comment by derduher** [comment]
As we no longer use url-join this appears to have been fixed `'/#/home'` renders as `<loc>https://hostname.com/#/list</loc>` `!` or no `!`
