### ISSUE TITLE
XML not valid

### ISSUE THREAD

**Issue by Aspie96** [ekalinin/sitemap.js#76]
I tried to generate a sitemap and to validate it with:
https://validator.w3.org/

And it does not validate.

This is not necessearly a problem, but it would probably be better to fix it.

(Thank you for this library).

**Comment by Aspie96** [comment]
Sorry, I apologize: my bad.
I copied the generated source code from Google Chrome ("view-source:…", which adds an extra line).

**Comment by ekalinin** [comment]
It's ok :)
