### ISSUE TITLE
Unit Test fails due to timezone offset

### ISSUE THREAD

**Issue by rauberdaniel** [ekalinin/sitemap.js#78]
The tests currently fail on my machine probably due to timezone offset (I’m currently in New Zealand, UTC +12) and the test fails because

(calculated by sitemap.js with input `lastmod` 2011-06-27 and timezone offset) 2011-06-28 ≠ 2011-06-27 (set in comparison string)

Seems like we should have a look at the date calculation.

**Comment by ekalinin** [comment]
Hey @rauberdaniel 

Yeah, i changed one place related to the TZ (e1abd0c43236019)
And test with this change looks good: 
  * https://travis-ci.org/ekalinin/sitemap.js/builds/140503724

What version of the node did you use?

**Comment by rauberdaniel** [comment]
@ekalinin I am using node 6.2.2
It might not be an issue for you or travis because you’re in a time zone closer to UTC (if that makes sense?).

**Comment by rauberdaniel** [comment]
@ekalinin #82 should fix this
