### ISSUE TITLE
Image loc and caption problems

### ISSUE THREAD

**Issue by silveur** [ekalinin/sitemap.js#83]
Hi, whenever I add an image with its caption I always end up being a wrong url such as:

`<url>
<loc>
https://URL
</loc>
<image:image>
<image:loc>https://URL/[object Object]</image:loc>
</image:image>
</url>`

The image:loc is wrong and the caption doesn't seem to appear...
The problem seems to be at ligne 383 in your sitemap.js file

**Comment by rauberdaniel** [comment]
@silveur that sounds like you haven't updated to the latest version of Sitemap.js

**Comment by Kronos66** [comment]
I had similar problem which appear when host name in main config was different than image host. I resolve this problem removing main host name.
```
 let readySiteMap = site.createSitemap({
                        cacheTime: 6000,
                        urls: urls
                    });
```

**Comment by silveur** [comment]
I'm using version 1.8 of sitemap.js which is latest. 
Can't figure out what's wrong tbh

**Comment by rauberdaniel** [comment]
@silveur would you show us the code excerpt how you call sitemap.js so that we can reconstruct it?

**Comment by silveur** [comment]
Basically the route looks like this:
`app.get('/sitemap.xml', function(req, res)
	{
		SEO.getSitemap(function(sitemapjson)
		{
			sitemap = sm.createSitemap(sitemapjson);
			sitemap.toXML( function (err, xml)
			{
				if (err) return res.status(500).end();
				res.header('Content-Type', 'application/xml');
				res.send(xml);
			});
		})
	});
`

And for each url that i add I try to add the image location such as:

`
for(var i=0 ;i<releases.length; i++)
						{
							var entry = { 
											url: releases[i].getUrl(), 
											changefreq: 'daily', 
											priority: 0.8, 
											lastmodISO: releases[i].updated.toISOString(),
											img: [{ url: String(releases[i].artwork), 
													caption: releases[i].getArtistNames() + ' - ' + releases[i].title }]
										}
							sitemap.urls.push(entry);
						}
`

**Comment by rauberdaniel** [comment]
Hey @silveur 
I found the issue with hostname and images as objects and fixed it with #84 
This issue should be solved as soon as it is merged and released. Thanks for the hint @Kronos66

**Comment by ekalinin** [comment]
Thank you @rauberdaniel so much!
Just released 1.8.1.

**Comment by silveur** [comment]
Really glad this is fixed 👍 
Thanks @rauberdaniel and @ekalinin

**Comment by silveur** [comment]
Thanks @rauberdaniel 
I'm guessing the CDATA prefix for the caption is there on purpose too?
