### ISSUE TITLE
an error in README

### ISSUE THREAD

**Issue by yi** [ekalinin/sitemap.js#85]
section: https://github.com/ekalinin/sitemap.js#example-of-sitemap-index-as-string

current:

`
var sm = require('sitemap')
  , smi = new sm.buildSitemapIndex({
      urls: ['https://example.com/sitemap1.xml', 'https://example.com/sitemap2.xml']
      xslUrl: 'https://example.com/style.xsl' // optional
    });
`

should be:

`
var sm = require('sitemap')
  , smi = sm.buildSitemapIndex({
      urls: ['https://example.com/sitemap1.xml', 'https://example.com/sitemap2.xml']
      xslUrl: 'https://example.com/style.xsl' // optional
    });
`

because `sm.buildSitemapIndex` is a static method.

**Comment by ekalinin** [comment]
Thanks!
