### ISSUE TITLE
Please add sitemap for video 

### ISSUE THREAD

**Issue by muhammadfaizan** [ekalinin/sitemap.js#88]
Support sitemap for videos, and is there anyway i can create sitemap for video pages
Thanks

**Comment by qtran-coursera** [comment]
+1 :] 
Спасибо, @ekalinin !

**Comment by ekalinin** [comment]
@qtran-coursera [Тебе спасибо за этот патч](https://translate.yandex.ru/?text=%D0%A2%D0%B5%D0%B1%D0%B5%20%D1%81%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE%20%D0%B7%D0%B0%20%D1%8D%D1%82%D0%BE%D1%82%20%D0%BF%D0%B0%D1%82%D1%87&lang=ru-en) #93 ! ;)
