### ISSUE TITLE
can you add a `fromXml()` method ? 

### ISSUE THREAD

**Issue by shakaIsReal** [ekalinin/sitemap.js#90]
This would be useful to add new data to existing sitemaps

**Comment by Birowsky** [comment]
how do you guys bypass this currently?

**Comment by sabuhinazarov** [comment]
The same problem as well :(

**Comment by godsmustbcrazy** [comment]
+ 1 Same problem. 

Trying to implement something where sitemap persists between deployments.

**Comment by FadiAboMsalam** [comment]
any updates on this guys because i need the same functionality 

i need to be able to read existing sitemap and add to it

**Comment by kuiperr005** [comment]
Same here! Any ideas regarding this?

**Comment by derduher** [comment]
#154 duplicates this.

**Comment by derduher** [comment]
Implemented. Feedback welcome.
