### ISSUE TITLE
Invalid UTF-8 characters

### ISSUE THREAD

**Issue by dquang-tran** [ekalinin/sitemap.js#99]
Not all UTF-8 characters are accepted in an XML document. [Here](https://www.w3.org/TR/REC-xml/#charsets) is the range of possible characters.
If you insert a character outside of this range, you get an invalid XML document that would give you "PCDATA invalid Char value .." error when you try to open it in chrome. 
Do you think it would be a good idea to add an input sanitizer that strips away all invalid characters?  
```
function utfForXml (input) {
    return input.replace(/[^\x09\x0A\x0D\x20-\xFF\x85\xA0-\uD7FF\uE000-\uFDCF\uFDE0-\uFFFD]/gm, '')
}
```

**Comment by rauberdaniel** [comment]
Sounds good to me. Maybe in combination with dropping a warning that characters have been removed or something similar.

**Comment by derduher** [comment]
Can you give an example of a character that is not supported? we've switched to an xml library since this code was created and this ticket may no longer be true.
